### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by flaviomb** [quic/aimet#100]
Hi all. After the installation of Qualcomm Aimet toolkit,  when I start python3 I get the following error:

```
Failed to import the site module
Traceback (most recent call last):
  File "/home/flavio/git/qualcomm_aimet_tool/build/staging/universal/lib/x86_64-linux-gnu/site.py", line 75, in <module>
    __boot()
  File "/home/flavio/git/qualcomm_aimet_tool/build/staging/universal/lib/x86_64-linux-gnu/site.py", line 49, in __boot
    addsitedir(item)  # noqa
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 169, in addpackage
    for n, line in enumerate(f):
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

I really don't know the reason of this error. Could you help me to solve this issue? Thanks in advance!

**Comment by flaviomb** [comment]
Here some update: When I reinstall the aimet tool and use it for the first time, the error does not appear. However, when I've try to run the example (or even open the python3 program) again, the error appears.

**Comment by quic-bharathr** [comment]
@flaviomb Do you still have this issue? Could you please tell after which step on this page did you see this error? And which example did you try to run?
https://github.com/quic/aimet/blob/develop/USAGE.md

Also could you please try it from a location other than your Linux home directory if possible?

**Comment by wangmaolin** [comment]
Hi @quic-bharathr  I have the same issue. I prepared the environment using the docker file. Everything goes fine until I get to "Set package and library paths". After I source the PYTHONPATH, I got this error even I only try to open the python interpreter.

**Comment by quic-akhobare** [comment]
So we have seen this error before. Check if there is a ":" at the end of your PYTHONPATH variable. This is not allowed.

**Comment by szherzdev** [comment]
Make sure there're no unexpected .pth files in the PYTHONPATH folders. In my case, it was one created by the quantsim.export().

**Comment by quic-bharathr** [comment]
@flaviomb @wangmaolin We're closing this Issue. If you still see this problem, please Reopen it.
