### ISSUE TITLE
 ImportError: cannot import name 'QuantizationDataType'

### ISSUE THREAD

**Issue by SatyamGaba** [quic/aimet#1039]
`from aimet_common.defs import QuantizationDataType`
gives the following error:
` ImportError: cannot import name 'QuantizationDataType'`

I am on aimet version 1.19.1, cuda 11.6, ubuntu 18.04

**Comment by quic-ssiddego** [comment]
Hi @SatyamGaba  It is available here : https://github.com/quic/aimet/blob/develop/TrainingExtensions/common/src/python/aimet_common/defs.py#L339
could you perhaps try the next version?
