### ISSUE TITLE
How to skip prun first layer in VGG16?

### ISSUE THREAD

**Issue by BoyuGuan** [quic/aimet#1069]
Hi @TingfengTang  and @LLNLanLeN Just wanted to add to your conversation above : "perhaps the best way to do this is to switch to Manual Mode instead of Auto. I think as long as we use Auto, pruning the first layer may not be possible." Even if you change from auto to manual, first layer should be output channel pruned - you should skip input prune always.

_Originally posted by @quic-ssiddego in https://github.com/quic/aimet/issues/774#issuecomment-956998882_

**Comment by BoyuGuan** [comment]
The struction of VGG16 as below:
` VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (18): ReLU(inplace=True)
    (19): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (20): ReLU(inplace=True)
    (21): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (22): ReLU(inplace=True)
    (23): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (24): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (25): ReLU(inplace=True)
    (26): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (27): ReLU(inplace=True)
    (28): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (29): ReLU(inplace=True)
    (30): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(7, 7))
  (classifier): Sequential(
    (0): Linear(in_features=25088, out_features=4096, bias=True)
    (1): ReLU(inplace=True)
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=4096, out_features=4096, bias=True)
    (4): ReLU(inplace=True)
    (5): Dropout(p=0.5, inplace=False)
    (6): Linear(in_features=4096, out_features=1000, bias=True)
  )
)`
It should skip the VGG.features.0, but 
`    auto_params = aimet_torch.defs.ChannelPruningParameters.AutoModeParams(greedy_params, modules_to_ignore=[  VGG.features.0])`
is wrong, I don't know how to fix it.

**Comment by quic-ssiddego** [comment]
@BoyuGuan could you add the error snippet for this? Do take a look at this code example for using modules_to_ignore https://github.com/quic/aimet/blob/d44b946dfb22850108ebd653fe8b3e9fbfe2124c/NightlyTests/torch/test_compress_example_torch.py#L391.

**Comment by BoyuGuan** [comment]
> 

Thank you! I fix it! it should be
 `auto_params = aimet_torch.defs.ChannelPruningParameters.AutoModeParams(greedy_params, modules_to_ignore=[ VGG.features[0]]`
not `auto_params = aimet_torch.defs.ChannelPruningParameters.AutoModeParams(greedy_params, modules_to_ignore=[ VGG.features.0]`.
The erro message misled me.
