### ISSUE TITLE
ModuleNotFoundError: No module named 'libpymo'

### ISSUE THREAD

**Issue by MPolaris** [quic/aimet#1090]
when I run ada_round.py
`
from aimet_tensorflow import batch_norm_fold as aimet_bnf
`
gives the following error:
`
  File "/data0/xiaohe/miniconda3/envs/aimet/lib/python3.7/site-packages/aimet_tensorflow/batch_norm_fold.py", line 44, in <module>
    import libpymo
ModuleNotFoundError: No module named 'libpymo'
`
I am on aimet version 1.19.1.py37, buntu 18.04, on conda sub environment.
python version is 3.7.11
AIMET_VARIANT=tf_cpu
release_tag=1.19.1.py37

**Comment by pablogsanchez** [comment]
You need to add the path to LD_LIBRARY_PATH:
example: 

export LD_LIBRARY_PATH=/home/user/anaconda3/envs/pytorch/lib/python3.6/site-packages/aimet_common/x86_64-linux-gnu/:$LD_LIBRARY_PATH

**Edit the path to your correct path**

**Comment by quic-ssiddego** [comment]
+ @quic-bharathr
