### ISSUE TITLE
How to load the exported model?

### ISSUE THREAD

**Issue by flaviomb** [quic/aimet#110]
I'm using this the api quantization tutorial which shows how to export the quantized model using this command 

`sim.export(path='./', filename_prefix='quantized_mnist', input_shape=input_shape`

When I'm use this piece of code, three files are generated: `quantized_mnist.pth`,` quantized_mnist.onnx` and `quantized_mnist.encodings`.

My question is: How to load the quantized model again using these three files? 

Thanks!

**Comment by quic-ssiddego** [comment]
Hi @flaviomb : Thank you for your query. If the user wants to save a QuantSim model with an intention to load it back later, then they should use the save_checkpoint() and load_checkpoint() methods (and, not the export method above).  Please let me know if you have further questions.

**Comment by jasonlovescoding** [comment]
Hi @quic-ssiddego thanks for the answer! Is it possible to manually modify the quantization parameters in the checkpoint model? I want to do a simulation with AIMET given parameters from other tools.

**Comment by quic-akhobare** [comment]
Hi @jasonlovescoding. Yes this is possible.

Given a model with a layer called conv1. You can write code like this
sim.model.conv1.output_quantizer.min = your min
sim.model.conv1.output_quantizer.max = your max
sim.model.conv1.output_quantizer.delta = your delta
sim.model.conv1.output_quantizer.offset = your offset

If doing the above, please set all 4 of these properties. For 8-bit quantization, delta = (max - min) / 255, offset = round(min/delta),
There is an assumption that 0 is represented by one of the integer values. And min <= 0, max >=0 but both max and min cannot be zero.

Also note that given a layer there are two possible quantizers - one for input and another for output. And one per parameter.

Let me know if you have further questions.

**Comment by quic-akhobare** [comment]
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
