### ISSUE TITLE
No module named 'aimet_torch'

### ISSUE THREAD

**Issue by pianogGG** [quic/aimet#111]
I follow this guid https://github.com/quic/aimet/blob/develop/USAGE.md  all are done successfully！But when I ran scripts , it hints
ModuleNotFoundError: No module named 'aimet_tensorflow' No module named 'aimet_torch'

**Comment by pianogGG** [comment]
BTW, where I can find the script in this tutorial video script https://quic.github.io/aimet-pages/index.html#video ? Can I run successfully follow this video?

**Comment by pianogGG** [comment]
I have solved the first problem

**Comment by kanybekasanbekov** [comment]
@pianogGG How did you solve it? I have faced the same problem...

**Comment by kanybekasanbekov** [comment]
I solved it.
According to instructions AIMET package would be available at `$WORKSPACE/build/staging/lib/`, however, in my case, they were saved to `$WORKSPACE/build/staging/universal/lib/`.
Thus I had to use the following commands to set environmental variables.

`export PYTHONPATH=$WORKSPACE/build/staging/universal/lib/x86_64-linux-gnu:$WORKSPACE/build/staging/universal/lib/python:$PYTHONPATH`

`export LD_LIBRARY_PATH=$WORKSPACE/build/staging/universal/lib/x86_64-linux-gnu:$WORKSPACE/build/staging/universal/lib/python:$LD_LIBRARY_PATH`
