### ISSUE TITLE
Exporting graph with fake quant nodes

### ISSUE THREAD

**Issue by macsmy** [quic/aimet#1113]
Hello, 
After performing QAT algorithms (such as Adaround or CLE), using the output session to create `QuantizationSimModel` model and exporting it, the resulting model has no fake quant nodes - only json file with corresponding statistics is available. Is it possible to export the model with fake quant nodes directly?

**Comment by quic-ssiddego** [comment]
@macsmy That is right - AIMET quantsim skips fake quant nodes during export. We do not support export with fake quant nodes with quantsim export functionality.

**Comment by macsmy** [comment]
@quic-ssiddego thanks for the reply. i have already implemented such functionality - it seems to work fine.

**Comment by quic-ssiddego** [comment]
@macsmy Great - would you like to contribute this utility to AIMET?

**Comment by macsmy** [comment]
@quic-ssiddego i think i can try to do it

**Comment by quic-kyunggeu** [comment]
We're recently adding support for exporting model with the quantization nodes present.
If you're using aimet_torch.v2, you can simply do `torch.onnx.export(sim.model)` and you will get an onnx graph with all the qtzn nodes in place.
