### ISSUE TITLE
I try to quantize deepspeech demo,but error happend

### ISSUE THREAD

**Issue by fmbao** [quic/aimet#1144]
`ImportError: /home/mi/anaconda3/envs/aimet/lib/python3.7/site-packages/aimet_common/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.7-linux-x86_64.egg/AimetTensorQuantizer.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v`

platform:Ubuntu 18.04
GPU: nvidia 2070
CUDA:11.1
pytorch
python:3.7

**Comment by quic-ssiddego** [comment]
@fmbao  Thank you for reporting this. @quic-bharathr could you help with this?

**Comment by cosperypf** [comment]
Hi, I have this error too, has anyone solved it？
I have a successfully build like here: https://github.com/quic/aimet/blob/develop/packaging/docker_install.md
"import aimet" run well, but  "from aimet_torch.batch_norm_fold import fold_all_batch_norms" will failed with this error:
----
ImportError: AimetTensorQuantizer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

**Comment by cosperypf** [comment]
Hi, I have this error too, has anyone solved it？
I have a successfully build like here: https://github.com/quic/aimet/blob/develop/packaging/docker_install.md
"import aimet" run well, but "from aimet_torch.batch_norm_fold import fold_all_batch_norms" will failed with this error:
---
ImportError: AimetTensorQuantizer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

**Comment by cosperypf** [comment]
Hi, I have this error too, has anyone solved it？
I have a successfully build like here: https://github.com/quic/aimet/blob/develop/packaging/docker_install.md
"import aimet" run well, but "from aimet_torch.batch_norm_fold import fold_all_batch_norms" will failed with this error:
ImportError: AimetTensorQuantizer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

**Comment by cosperypf** [comment]
finally I fixed it by reduce the pytorch version from 1.11 to 1.9.1, and it works well now
