### ISSUE TITLE
ImportError: /usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/AimetTensorQuantizer.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tenso

### ISSUE THREAD

**Issue by fmbao** [quic/aimet#1165]
when I run `deepspeech2_quanteval.py` ,the Error throw `ImportError: /usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu/aimet_tensor_quantizer-0.0.0-py3.6-linux-x86_64.egg/AimetTensorQuantizer.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tenso`

**Comment by fmbao** [comment]
upupup

**Comment by quic-ssiddego** [comment]
cc @quic-bharathr could you please take a look at this.

**Comment by quic-sendilk** [comment]
please retry in the newer release and reopen its still an issue.
