### ISSUE TITLE
About the adaround 

### ISSUE THREAD

**Issue by zhenhouhong** [quic/aimet#1273]
I run the aimet tensorflow in 1.9.1 version.
In adaround example, all parameters are default, not change the code.

After finish the running, I found the export quantized model of resnet50 is only smaller 1M than the original model. 
This original model is 99M, is .h5 file. The quantized model is 98M.

**Comment by quic-akhobare** [comment]
Hi @zhenhouhong. AIMET AdaRound does not quantize the model, it optimizes the model for a quantized target device. E.g. if you want to run this resulting model on a SnapDragon device you can use the SnapDragon Neural Processing SDK to quantize the model and then run on target.

Hope that answers your question. Closing this for now. Please re-open if you have a follow-up question.
