### ISSUE TITLE
Channel pruning for SSD model supported?

### ISSUE THREAD

**Issue by krebin** [quic/aimet#1281]
Hello, I am trying to use AIMET to prune an SSD model in tensorflow. Upon looking at example code, I see that an evaluation function is required that measures accuracy. Is the API compatible with SSD architecture and is there an example I have not seen? Thanks

**Comment by quic-ssiddego** [comment]
Hi @krebin Could you please provide a snippet of what you have tried so far? And, also - have you checked this example? https://github.qualcomm.com/qualcomm-ai/aimet-model-zoo/blob/aimet_hf_transformer_model_definitions/zoo_tensorflow/Docs/SSDMobileNetV2.md
