### ISSUE TITLE
Issue with make install inside docker image

### ISSUE THREAD

**Issue by erliding** [quic/aimet#129]
After launching docker container with `./buildntest.sh -i` I got the following error when trying to build aimet:
```
CMake Error at TrainingExtensions/torch/cmake_install.cmake:73 (file):
  file INSTALL cannot find "/home/eding/projects/build/artifacts/site.py".
Call Stack (most recent call first):
  TrainingExtensions/cmake_install.cmake:43 (include)
  cmake_install.cmake:43 (include)
```
Any way to fix it?

Thanks!

**Comment by ishan-sahu** [comment]
I faced the same issue. It seems that the file is missing. The solution provided in the similar issue #108 solved it for me.  Here: https://github.com/quic/aimet/issues/108#issuecomment-655196783

**Comment by erliding** [comment]
Great! Thanks for the link :-)

**Comment by vinaygcode** [comment]
Hi @erliding ,

Can you please confirm what is the setuptools version in your machine? installing setuptools version = 41.0.1 should resolve this issue. We are suspecting that you do not have the correct version of setuptools installed. If your version is incorrect, can you please try to update the package, and compile it again (after removing all existing files in build directory, if you have already compiled in same workspace), and without using work around of manually copying the site.py mentioned above. 

Please install setuptools with below command:

`!pip3 install setuptools==41.0.1`

Thanks,
Vinay

**Comment by quic-akhobare** [comment]
Since the issue seems resolved, I will close this. Please reopen or create a new issue if there are further questions.
