### ISSUE TITLE
Does version 1.20 support per-channel?

### ISSUE THREAD

**Issue by ghost** [quic/aimet#1302]
Try to modify per_channel_quantization in default_config.json and set it to True, but it doesn't seem to work

**Comment by quic-ssiddego** [comment]
Hi @17818587795 Were you trying this with PyTorch or TF model? Here's an example config to be added to enable per channel quantization on a given PyTorch Model : https://github.com/quic/aimet/blob/a0c7b3bb88cad769dc8130bf3a87a6c86128ba69/TrainingExtensions/torch/test/python/test_per_channel_quantization.py#L788.

**Comment by quic-akhobare** [comment]
I hope the above response answered your question @17818587795. Closing the ticket. Please re-open if you have a follow-up question or create a new issue.
