### ISSUE TITLE
Release tag=1.20.0 has version conflict

### ISSUE THREAD

**Issue by hammer422** [quic/aimet#1310]
When I run this command
`python3 -m pip install AimetTensorflow-tf_cpu_1.20.0-cp36-cp36m-linux_x86_64.whl`

I get the following error

The conflict is caused by:
    aimettensorflow tf-cpu-1.20.0 depends on h5py==2.9.0
    tensorflow 2.4.0 depends on h5py~=2.10.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by quic-ssiddego** [comment]
@changewOw  Thank you for reporting this. @quic-bharathr could you please take a look at this.

**Comment by navaravan** [comment]
Hi @quic-ssiddego 

Any update on the above issue?

**Comment by quic-akhobare** [comment]
Hi @navaravan - please use the latest AIMET release. This issue is resolved now. Closing the ticket.
