### ISSUE TITLE
Issue while running aimet: liblapacke.so.3: undefined symbol: chesv_aa_2stage_

### ISSUE THREAD

**Issue by ashwinjosephk** [quic/aimet#1360]
Hello Team,
I am using a system having Ubuntu 18.04.

I was following the instructions mentioned at https://github.com/quic/aimet/blob/develop/packaging/install.md 
I downloaded the wheel files from https://github.com/quic/aimet/releases for version 1.20.
Since I am focusing on Pytorch, I downloaded the following wheel files: Aimet-torch_cpu_1.21.0-cp36-cp36m-linux_x86_64.whl, AimetCommon-torch_cpu_1.21.0-cp36-cp36m-linux_x86_64.whl, AimetTorch-torch_cpu_1.21.0-cp36-cp36m-linux_x86_64.whl and installed them via pip.

Also since I am using a virtual environment for installation, I set the path of aimet_common located in virtual environment.
Now I am trying to execute the following code snippet:

```
import torch
from torchvision.models import resnet18

model = resnet18(pretrained=True)

from aimet_torch.model_preparer import prepare_model
prepared_model = prepare_model(model)

from aimet_common.defs import QuantScheme
from aimet_torch.quantsim import QuantizationSimModel
input_shape = (1, 3, 224, 224)
dummy_input = torch.randn(input_shape)

exit()
```

But I end up with the issue as follows:
```
Traceback (most recent call last):
  File "experiment.py", line 6, in <module>
    from aimet_torch.model_preparer import prepare_model
  File "/home/ubuntu/ashwin/venv3/lib/python3.6/site-packages/aimet_torch/model_preparer.py", line 47, in <module>
    from aimet_torch.utils import get_device
  File "/home/ubuntu/ashwin/venv3/lib/python3.6/site-packages/aimet_torch/utils.py", line 48, in <module>
    from aimet_common.defs import QuantScheme, QuantizationDataType, MAP_QUANT_SCHEME_TO_PYMO
  File "/home/ubuntu/ashwin/venv3/lib/python3.6/site-packages/aimet_common/defs.py", line 46, in <module>
    import libpymo
ImportError: /usr/lib/x86_64-linux-gnu/liblapacke.so.3: undefined symbol: chesv_aa_2stage_
```

Could you help me with resolving this issue?

**Comment by onlyinheaven** [comment]
try install blas
`conda install -c conda-forge blas`

**Comment by quic-hitameht** [comment]
Hi @ashwinjoseph95 Thanks for reporting this issue. AIMET has dependency on `liblapacke`. Could you please try installing the `liblapacke` first? 

`apt-get install liblapacke`

Please let us know if you have further questions.
