### ISSUE TITLE
Not able to setup AIMET 1.21.0 on Ubuntu-18

### ISSUE THREAD

**Issue by navaravan** [quic/aimet#1387]
Hi Team

When I run this command
$ python3 -m pip install AimetTensorflow-tf_gpu_1.21.0-cp36-cp36m-linux_x86_64.whl

I get the following error:
ERROR: Cannot install AimetTensorflow and aimettensorflow==tf-gpu-1.21.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    aimettensorflow tf-gpu-1.21.0 depends on h5py==2.9.0
    tensorflow-gpu 2.4.0 depends on h5py~=2.10.0

>How to proceed further ?
>Thanks in advance

**Comment by quic-bharathr** [comment]
Hi @navaravan , are you still having this issue with the latest version? https://github.com/quic/aimet/releases/tag/1.25.0
