### ISSUE TITLE
AIMET-1.22.0 supports TF-2.x ?

### ISSUE THREAD

**Issue by navaravan** [quic/aimet#1404]
Hi @quic-ssiddego @Rohan-Chaudhury  and other collaborators

>Thanks for sharing the work

> I wanted to know whether the latest AIMET-1.22.0 API's supports tensorflow 2.X, I'm asking this because I can see tf.compat.v1 called in most of the places, that means you are using Tensorflow-1 APIS.

>Thanks in advance.

**Comment by koon-kai** [comment]
I also want to know.

**Comment by xxr11** [comment]
I also want to know.

**Comment by koon-kai** [comment]
I tested it on tf2.x, but it is not supported.

**Comment by MPolaris** [comment]
I tested it on tf2.5, and same as you, it seems only support tf<1.15

**Comment by quic-akhobare** [comment]
Hi All. AIMET 1.22.0 supports both TF 1.15 and TF 2.4. Note that this means the model supported for the tensorflow APIs needs to be a TF session and also the training/eval pipeline needs to work with a modified TF session.

In addition to this, you will see that the latest AIMET release 1.23.0 also adds support for Keras APIs. So you can pass a Keras model to AIMET and use a Keras pipeline for eval/training. Supported version is still TF 2.4.

**Comment by quic-akhobare** [comment]
Tagging @MPolaris @koon-kai @navaravan 

Closing the ticket - if you have further questions, please re-open or create a new issue.
