### ISSUE TITLE
Documentation Related Issue 

### ISSUE THREAD

**Issue by yash88600** [quic/aimet#15]
Does the library supports RNN based model, as you haven't mentioned anything about it and also not mentioned any benchmarks on a RNN based model??

**Comment by quic-akhobare** [comment]
Thanks for the query. Currently AIMET does not support RNN based models – both for model quantization and model compression. We will update the documentation to make this more clear. 

More information on the following would be useful
•	Which particular feature were you planning to use with RNN models?
•	Which RNN-based models are you interested in trying AIMET features on?

We are considering adding support for RNN (including LSTM/GRU) quantization in the future. Please let us know if you are interested in contributing to AIMET.

**Comment by yash88600** [comment]
I would like to try AIMET on the tacotron 2(TTS) model, (both pruning and quantization).

Talking about the contribution, currently i don't think i have enough knowledge so as to contribute, but will definitely contribute in future. 
Thank you
