### ISSUE TITLE
could not visit User Guide and API Docs page！

### ISSUE THREAD

**Issue by HaihuaQiu** [quic/aimet#150]
Hi, I could not visit User Guide and API Docs web page, it appears:This site can’t be reachedquic.github.io refused to connect. ERR_CONNECTION_REFUSED. SO how to visit these web pages?

**Comment by quic-ssiddego** [comment]
Hi @HaihuaQiu Did you try this link? https://quic.github.io/aimet-pages/AimetDocs/api_docs/index.html . Please do let us know if you still have trouble accessing it.

**Comment by quic-akhobare** [comment]
@quic-fmayer, this is a useful comment from @HaihuaQiu 

Is it feasible to have some content on https://quic.github.io/ that perhaps points to AIMET at present. If/when there is more content than AIMET it can serve as a useful landing page. Can you please check with @craigez ?

**Comment by HaihuaQiu** [comment]
Thanks, I have solved this problem, because this URL is banned by my company.
