### ISSUE TITLE
the accuracy during quantization aware training decreased and keep at 0.1

### ISSUE THREAD

**Issue by roycyh** [quic/aimet#1517]
hello, when I running the example quantization aware training or range learning, the top 1 accuracy decreases to 0.1 and keeping unchanged. Did anyone meet this problem?

**Comment by quic-mangal** [comment]
@roycyh, thanks for reaching out. When you create a sim object and perform
`sim.compute_encodings` and perform evaluation, do you still get this accuracy drop? 

One recommendation is to visualize the weight ranges (you can use AIMET APIs to do the same) and if the weight ranges are very large you can try using the Cross Layer Equalization feature.
