### ISSUE TITLE
why happends this problem after using cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../aimet && make -j8

### ISSUE THREAD

**Issue by HaihuaQiu** [quic/aimet#159]
/aimet/build/TrainingExtensions/torch/src/setup.py", line 40, in <module>
    from torch.utils.cpp_extension import BuildExtension, CppExtension
ModuleNotFoundError: No module named 'torch'
TrainingExtensions/torch/CMakeFiles/TorchCppOps.dir/build.make:61: recipe for target 'TrainingExtensions/torch/build/timestamp' failed
make[2]: *** [TrainingExtensions/torch/build/timestamp] Error 1
CMakeFiles/Makefile2:760: recipe for target 'TrainingExtensions/torch/CMakeFiles/TorchCppOps.dir/all' failed
make[1]: *** [TrainingExtensions/torch/CMakeFiles/TorchCppOps.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I do not solve this problem

**Comment by HaihuaQiu** [comment]
I focus on TrainingExtensions/torch/CMakeFiles/TorchCppOps.dir/build.make, find below: /miniconda3/bin/python3 /home/XXX/Documents/aimet/aimet/build/TrainingExtensions/torch/src/setup.py。 
But docker image package setup up in /usr/bin/python3, so I modify python adress to this. But when I restart cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../aimet && make -j8 command, the same mistake happend in build.make. It still appear /miniconda3/bin/python3 /home/XXX/Documents/aimet/aimet/build/TrainingExtensions/torch/src/setup.py.
So what should I do to solve this problem???

**Comment by HaihuaQiu** [comment]
I have solved this problem, first, delete ${WORKSPACE}/build folder, then mkdir build and cd build,  conda deactivate base envs, last you can successful build this project using cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../aimet && make -j8

**Comment by quic-ssiddego** [comment]
Hi @HaihuaQiu  Thank you for reporting the issue and also a corresponding resolution. Please do let us know if you have any other issue. Closing this.
