### ISSUE TITLE
Error when using Dockerfile

### ISSUE THREAD

**Issue by anirudth** [quic/aimet#17]
Building the Docker image directly from the given Dockerfile results in an error. The error got alleviated when I replaced "pip==9.0.1" with "pip" in the Dockerfile.

**Comment by quic-akhobare** [comment]
Thanks @anirudth for reporting the issue and your workaround. Could you please paste the error message so we can understand the error better?

**Comment by anirudth** [comment]
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vt15b5c1/imagecodecs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ihx3kbo_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vt15b5c1/imagecodecs/
You are using pip version 9.0.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/bash -c pip3 --no-cache-dir install         attrs==19.1.0         wget         behave==1.2.6         blosc==1.8.1         cffi         click         cython==0.29.10         h5py==2.10.0         ipykernel==4.8.2         keras==2.2.4         lmdb==0.95         opencv-python==4.1.0.25         pillow==6.2.1         pluggy==0.12.0         protobuf==3.7.1         pybind11==2.2.3         pylint==2.3.1         pytest==4.6.5         pytest-cov==2.6.1         pytorch-ignite==0.1.0 &&         pip3 install  https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl &&         pip3 install  https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl &&         pip3 --no-cache-dir install         scikit-image         scikit-learn==0.19.1         scipy==1.1.0         sphinx==2.1.1         sphinx-autodoc-typehints==1.6.0         tb-nightly==1.14.0a20190517         tensorboardX==1.7         tensorlayer==2.1.0         torchtext==0.3.1         tqdm==4.32.2 &&     python3 -m ipykernel.kernelspec' returned a non-zero code: 1`

**Comment by quic-bharathr** [comment]
@anirudth We assume that unpinning the pip package works for you. We will look into formally upgrading the pip package version and incorporate the fix.

**Comment by quic-akhobare** [comment]
Pretty old ticket. Assuming that you are no longer facing this - @anirudth. Please create a new issue if needed.
