### ISSUE TITLE
bug: release AimetTorch-torch_gpu_1.23.0.whl content is incorrect

### ISSUE THREAD

**Issue by leemengxing** [quic/aimet#1794]
hi，I want to use quant_Analyzer function, which needs to be upgraded to 1.23.0. so 
I use the whl package provided：https://github.com/quic/aimet/releases/tag/1.23.0，but i found the content is incorrect. please check it, thks.

![image](https://user-images.githubusercontent.com/24696984/208287019-48540c4e-dc6e-4a96-8df5-75264f49bad8.png)

**Comment by leemengxing** [comment]
@aimetci

**Comment by quic-hitameht** [comment]
hi @leemengxing Can you try using the latest release 1.24.0 and let us know if you run into any issues.
