### ISSUE TITLE
Installation requires too much human input

### ISSUE THREAD

**Issue by anirudth** [quic/aimet#18]
It would be highly appreciated if you could provide a shell script that automates all the commands required to build the libraries, install and set paths. Also, it would be highly appreciated if you could include library installation procedures within the Dockerfile so that the Docker container with AIMET could be spun up in one go for experiments (instead of manually typing and debugging every line).

**Comment by quic-akhobare** [comment]
We are working on making the installation steps simpler. Should see these changes getting released over the next month. Closing this ticket for now.
