### ISSUE TITLE
ModelValidator check failed when Abs op exist

### ISSUE THREAD

**Issue by lilian0118** [quic/aimet#1851]
The model is below:

```
class Abs(torch.nn.Module):
    def __int__(self):
        super(Abs, self).__int__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.abs(x)


class ModelWithAbsNodes(torch.nn.Module):
    def __init__(self):
        super(ModelWithAbsNodes, self).__init__()
        self.linear = torch.nn.Linear(2, 5)
        self.aimet_abs = Abs()

    def forward(self, x):
        x = self.linear(x)
        return self.aimet_abs(x)


    model = ModelWithAbsNodes()
    model.eval()
    input_tensor = torch.randn(1, 2)
    prepared_model = prepare_model(model)
    ModelValidator.validate_model(prepared_model, model_input=input_tensor)
```

The result:

The following functional ops were found. The parent module is named for ease of locating the ops within the model definition.
	**abs_1**          parent module: GraphModule

2023-01-10 17:48:07,886 - Utils - INFO - The following validator checks failed:
2023-01-10 17:48:07,886 - Utils - INFO - 	<function validate_for_missing_modules at 0x7f43d9b28dc0>

How can I solve this problem? Thanks.

**Comment by quic-hitameht** [comment]
@lilian0118 Modules in the pytorch library namespace (starting with torch.nn) are leaf modules by default. All the other modules (aimet_abs()) are traced through in symbolic tracing. One way to fix this is to treat aimet_abs() module as leaf module and you can achieve this by passing it's reference to `modules_to_ignore` parameter in `prepare_model` API.

`prepared_model = prepare_model(model, modules_to_exclude=[model.aimet_abs])`

**Comment by SEMLLYCAT** [comment]
The following fuctional ops were found. The parent module is named for ease of locating the ops within the model definition.
zeros_10     parent module: Model
Concat_17  parent module: Model
my forward like this:

def forward(self, x):
     pad_0 = torch.zeros([x.shape[2], 2], device=x.device).unsqueeze(0).unsqueeze(0)
     x = torch.cat((x, pad_0), -1)
thanks
