### ISSUE TITLE
Unsupported op type

### ISSUE THREAD

**Issue by Dawsonqw** [quic/aimet#1982]
`2023-03-09 07:40:42,685 - Quant - INFO - Unsupported op type Squeeze
2023-03-09 07:40:42,685 - Quant - INFO - Unsupported op type Pad
2023-03-09 07:40:42,685 - Quant - INFO - Unsupported op type Mean`
hi.I had this problem. Is there a tutorial that solves this?

**Comment by quic-mangal** [comment]
@haohao-qw Thanks for reporting this. Could you provide some more context so that we could look into this?

**Comment by quic-klhsieh** [comment]
@haohao-qw , to confirm, are you using the PyTorch framework when seeing this message?
The op types identified here are meant to refer to TensorFlow specific ops, and these lines can be disregarded when using aimet_torch and the PyTorch framework.
