### ISSUE TITLE
Update the "Setup" section in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shiannn** [quic/aimet#2022]
Currently the file `USAGE.md` is replaced by `docker_install.md`.
The issue is for fixing the mention to `USAGE.md` in `CONTRIBUTING.md`.

**Comment by quic-akhobare** [comment]
Thanks for catching this. @shiannn - do you mind submitting a PR for this?

**Comment by shiannn** [comment]
Fixed by #2025
