### ISSUE TITLE
Could you please create a new release now that there is support for torch 1.13?

### ISSUE THREAD

**Issue by V0XNIHILI** [quic/aimet#2023]

**Comment by quic-akhobare** [comment]
Hi @V0XNIHILI  - thanks for the request. Some testing is pending with PyTorch 1.13. A release will be created and the right install instructions added after that. Meanwhile, if you are able to build AIMET, you can use the tip to test out AIMET with PyTorch 1.13 and give us feedback.

**Comment by quic-akhobare** [comment]
Closing this ticket for the present.

**Comment by V0XNIHILI** [comment]
Unfortunately I have not yet been able to succesfully build AIMET with PyTorch 1.13: I got quite far in the process, but some steps at the end fail (missing Rust compiler) but I can't work around those as I am working on a cluster and do not have `sudo` rights to install the remaining packages.

**Comment by quic-akhobare** [comment]
I see no worries. Thanks for your response. We will update with a release supporting PyTorch 1.13 when testing is completed. I don't have an ETA yet.

**Comment by 666DZY666** [comment]
When will torch1.13 be supported?
