### ISSUE TITLE
Mistakes on quantsim_code_example.py

### ISSUE THREAD

**Issue by shiannn** [quic/aimet#2063]
1. The function `pass_calibration_data(sim_model)` needs an another parameter since it will get arguments for forwards like [here](https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/src/python/aimet_torch/quantsim.py#L302).
2. The variable `sim` should be `quant_sim`.

**Comment by quic-akhobare** [comment]
Thanks @shiannn. Could you please raise a PR for these fixes?

**Comment by quic-mangal** [comment]
@shiannn, thanks for working on these changes. Closing this issue since this was resolved. If you have any further questions please re-open/ file another issue. Thanks
