### ISSUE TITLE
Error while install aimet_torch

### ISSUE THREAD

**Issue by kcArtemis** [quic/aimet#2138]
ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cu111 (from aimettorch) (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.9.1+cu111
![image](https://user-images.githubusercontent.com/77401839/232867629-4ba38ae4-ad50-44a5-b4af-c85adb9bdd45.png)

**Comment by kcArtemis** [comment]
Python version which Im using is 3.8.10

**Comment by quic-mangal** [comment]
@kcArtemis, the google colab instructions might be outdated. Could you try installing the wheel file instead- https://quic.github.io/aimet-pages/releases/1.25.0/install/index.html

**Comment by kcArtemis** [comment]
@quic-mangal so while installing aimettorch module if this wan't work,there is no torch module created because of that error,
please can you give other way for solving this?
