### ISSUE TITLE
quantisim model export onnx model

### ISSUE THREAD

**Issue by wangwenbin1991** [quic/aimet#2169]
Hello everyone
I tried to export onnx model use func quant_sim.export() after QAT, but when test the output onnx model and pth model, both of them got same wrong output tensor, which value are very large integer(near 1e7). Could you help me fix this problem?

**Comment by wangwenbin1991** [comment]
the right output tensor is like this:
tensor([[[[-19.9919],
          [-21.4649],
          [-25.2529],
          ...,
          [-17.6770],
          [-17.6770],
          [-17.6770]],

and the export onnx and pth model's infer result tensor is below:
tensor([[[[ -74192752.],
          [-152308432.],
          [-167405504.],
          ...,
          [ -31270196.],
          [ -31270196.],
          [ -31270196.]],

**Comment by quic-mangal** [comment]
@wangwenbin1991, are you trying to run quantized inference on the exported model? The model that is exported does not have any simulation ops, so what you can do is, create a sim from the newly loaded model, use- 

`load_encodings_to_sim` 
API (under quantsim.py) to load the exported JSON encodings and perform quantized inference

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue.
