### ISSUE TITLE
how to use layers_to_ignore to avoid some layer to be quantized

### ISSUE THREAD

**Issue by HaihuaQiu** [quic/aimet#220]
Hi, I use quantsim to quantize full model, but I want to some layer not to be quantized, how to use layers_to_ignore to avoid some layer to be quantized???

**Comment by quic-ssiddego** [comment]
@HaihuaQiu  Thank you for your query. An example that uses layers_to_ignore configuration with a PyTorch QuantSim model is available here : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py
Please refer : test_layers_to_ignore()

**Comment by HaihuaQiu** [comment]
Thank you! I want to use prelu or leakyrelu in quantize model，but it seems to make mistakes. Can AIMET supports these ops?

**Comment by quic-akhobare** [comment]
> Thank you! I want to use prelu or leakyrelu in quantize model，but it seems to make mistakes. Can AIMET supports these ops?

These layers should be supported. What kind of error did you observe? If you can elaborate on "it seems to make mistakes", that will help us understand the issue better.

**Comment by quic-akhobare** [comment]
No update in a while.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
