### ISSUE TITLE
Mistake in the comment in the Adaround example script

### ISSUE THREAD

**Issue by mstaczek** [quic/aimet#2208]
Sample usage script for Adaround contains a mistake in the comment: [Examples/torch/quantization/adaround.py](https://github.com/quic/aimet/blob/d11f625cdf15996474398087c124082490ab5404/Examples/torch/quantization/adaround.py#LL181C4-L183C4)

This comment mentions CLE and BC methods instead of the Adaround method.

According to [contribution rules](https://github.com/quic/aimet/blob/develop/CONTRIBUTING.md) I could do a PR to fix this comment and possibly other typos in this file. I am happy to help ;)

**Comment by quic-mangal** [comment]
@mstaczek Thanks for your contribution, I am closing this issue since the PR was already merged.
