### ISSUE TITLE
Installation on Ubuntu instructions error

### ISSUE THREAD

**Issue by wjf37** [quic/aimet#2256]
For the installation instructions page for Ubuntu there are two code blocks for `export AIMET_VARIANT=<variant_string>` when the second one should be for `export release_tag=<release_tag>` from [install.md](https://github.com/quic/aimet/blob/611488d9cd29d4a937a94e001d3cb95e928695ae/packaging/install.md).

**Comment by quic-mangal** [comment]
@wjf37, thanks for catching this. Would you like to create a PR for fixing this?
