### ISSUE TITLE
Inquiry about version 1.27 and its updates

### ISSUE THREAD

**Issue by topsy404** [quic/aimet#2362]
I happened to notice that 1.27 was released 5 days ago, and I am quite interested in exploring the new features and updates. However, it seems that the information regarding what's new is still marked as TODO. I understand that things can get busy, but I was wondering if you might have forgotten to update it. I would greatly appreciate it if you could kindly provide the details. Thank :)

**Comment by quic-mangal** [comment]
It has been updated. Thanks for pointing it out.

**Comment by quic-mangal** [comment]
Closing the issue. Please re-open it if you have any further questions
