### ISSUE TITLE
onnx simplifier

### ISSUE THREAD

**Issue by Zagreus98** [quic/aimet#2422]
Hi, is there a way to use the [onnx simplifier](https://github.com/daquexian/onnx-simplifier)  without affecting the generated encodings after quantization?  I saw this [PR ](https://github.com/quic/aimet/pull/1583) integrated this feature but I didn't find anywhere in the docs how to enable it.

**Comment by quic-mangal** [comment]
@quic-sendilk, could you help reply to this?

**Comment by quic-sendilk** [comment]
@Zagreus98, we have enabled an experimental feature to execute onnx simplifier with few addtional constrain.

if you require invocation of onnx simplification during export phase of quantization simulation. you could enable by setting the experimental flag as shown below:

```py
from aimet_torch import onnx_utils 
onnx_utils.simplify_onnx_model = True
quantsim.export(...)
```

**Comment by Zagreus98** [comment]
Thanks for the fast reply @quic-sendilk . If I set `onnx_utils.simplify_onnx_model = True` this should also work with the AutoQuant API right (where everything is saved automatically after each quantization method)?

And another question, do you know what are the additional constrains? I experimented a bit and  I saw that there are less simplifications done in comparison with simply running the simplifier on the resulted onnx. I observed that the impact of the simplifier is huge on the inference time (for example I reduced the inference time 7 times by directly running the simplifier and then doing the quantization through QNN).

**Comment by escorciav** [comment]
@Zagreus98 Can you share the name of the models (or details about the arch & size) you're simplifying & quantifying through QNN?
We're trying to bypass the QNN quantization by using the overriding parameters from AIMET. However, it's painful 🤕  as the synergy between Qualcomm:AIMET & Qualcomm:QNN (AI Direct SDK) feels brittle. Perhaps, I'm using it wrong 😓 .

**Comment by quic-sendilk** [comment]
Sorry, for the delayed response
> If I set `onnx_utils.simplify_onnx_model = True` this should also work with the AutoQuant API right (where everything is saved automatically after each quantization method)?

 Yes, please set this flag before invoking AutoQuant API

> And another question, do you know what are the additional constrains? 

the primary need to export a onnx model in the context quantization is to assign encoding to onnx activation tensors based on quantization simulation. To achieve this, the exported onnx model incorporates a few additional marker elements in the graph to allow consistent mapping between torch layer and onnx operator. So, in theory, these marker elements might prevent full scope of optimization e.g. constant fold etc.

**Comment by Zagreus98** [comment]
@escorciav We have issues with this synergy too, (is a yolov5 type architecture), for the moment we use only QNN because it applies simplify fully without aimet encodings and the model is much faster. Will close this for the moment. Thanks for clarifying @quic-sendilk
