### ISSUE TITLE
ModuleNotFoundError: No module named 'aimet_quantsim'

### ISSUE THREAD

**Issue by zyt1024** [quic/aimet#2436]
Hello, I am using the  `AIMET `version is `1.27.0` ,I referred to[ the document.](https://docs.qualcomm.com/bundle/publicresource/topics/80-64748-1/model_updates.html) When I tried to export the model, the following error was reported:
``` bash
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[33], line 1
----> 1 from aimet_quantsim import export_all_models

ModuleNotFoundError: No module named 'aimet_quantsim'
```

**Comment by quic-mangal** [comment]
@quic-akhobare could you help answer this. Thanks

**Comment by quic-mangal** [comment]
@zyt1024, when you downloaded the NB, do you see a aimet_quantsim.py file in the same folder as your NB?

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue.
