### ISSUE TITLE
Bypass QNN SDK quantization with AIMET

### ISSUE THREAD

**Issue by escorciav** [quic/aimet#2444]
Dear team,

Could you kindly confirm if any SDK quantization is disregarded when using AIMET encoding as part of [model conversion of qnn](https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-50/tools.html#qnn-onnx-converter), `--quantization_overrides`?
I assume that the quantization step is skipped when using AIMET encodings. In other words, do I have to use the same `--input_list`?

It would be great to clarify the precise scope & synergy between both Qualcomm software tools.
- AIMET
- QNN, AI Engine Direct SDK

**Comment by quic-akinlawo** [comment]
Hello @escorciav, 

Quantization still happens when AIMET encodings are passed, as not all operations that show up in the converted graph output (QNN model .cpp) will have encodings generated by AIMET. This is because the conversion step may translate ops, match patterns or introduce entirely new operations.

You do not typically have to use the same input list i.e. you may use more inputs for AIMET and less for QNN. The important thing to ensure is that the input list used is a representative sample of your dataset.

**Comment by shuyuan-wang** [comment]
> Reference in new

Hi,
does this mean the evaluation result after QAT does not necessarily reflect on the result on .so/.bin model if the PTQ result is really bad.

**Comment by shuyuan-wang** [comment]
> Hello @escorciav,
> 
> Quantization still happens when AIMET encodings are passed, as not all operations that show up in the converted graph output (QNN model .cpp) will have encodings generated by AIMET. This is because the conversion step may translate ops, match patterns or introduce entirely new operations.
> 
> You do not typically have to use the same input list i.e. you may use more inputs for AIMET and less for QNN. The important thing to ensure is that the input list used is a representative sample of your dataset.

Hi,
does this mean the evaluation result after QAT does not necessarily reflect on the result on .so/.bin model if the PTQ result is really bad.

**Comment by escorciav** [comment]
On-device AI is an art.
- There is academic research.
- Industry research
- ML on-device engineering

What's yours?

To bring stuff on-device, my pipeline is
1. Get an ONNX file
2. Use PTQ & QNN (assuming that your devices have Qualcomm brand, e.g., Snapdragon)
3. Use AIMET for custom PTQ (adaround, etc.)
    - W8A16, don't bother. 90% is lossless.
    - W8A8, bother yourself.
4. Still not meet the sweep spot (accuracy, latency)
    - QAT for W8A8. Good luck!
    - Mixed-precision, supported in AIMET Pro (Good luck!). Too slow for my taste. #2642 
    
    
Good luck!
