### ISSUE TITLE
Unable to access sample dockerfiles. Overall unable to set up on the PC directly due to Dependencies...

### ISSUE THREAD

**Issue by ashar6194** [quic/aimet#245]
Hi,

I am unable to access the sample DockferFiles, the links for which are provided here-
https://github.com/quic/aimet/blob/develop/packaging/docker_install.md#setup-the-environment

Am i missing on something?

Also, Can you please provide info about how to maybe set this up without Docker on the PC directly? Ideally it would be great to have one bash script which automatically installs all the required dependencies.

Thanks,

**Comment by ashar6194** [comment]
For example, when I was building the makefile on a new PC, it mentioned it was unable to find OpenCV... I think would be great if the installation scripts are also
 tried on brand new PCs which don't have any pre-installed libraries

**Comment by quic-bharathr** [comment]
Hi @ashar6194 Sorry the URL was incorrect. Please find the docker file here:
https://github.com/quic/aimet/blob/develop/Jenkins/Dockerfile

We'll fix the link shortly. Also we do not have an installation script at this time. if you do not want to use a docker, please install the dependencies on your machine using the above Dockerfile as a guide.

**Comment by quic-akhobare** [comment]
No update in a while.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
