### ISSUE TITLE
changing the name "activation_encodings" to "op_output_encodings" 

### ISSUE THREAD

**Issue by tensor1to5** [quic/aimet#2454]
Hi, I have a little suggestion that changing the name "activation_encodings" to "op_output_encodings" and the name "activation" to "op_output" would be more appropriate, because here activation is easily confused with the name of the activation names such as relu.

**Comment by quic-mangal** [comment]
In PyTorch & Keras, we have both Input and output quantization possible, so for a generic name, activations was chosen.

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue.
