### ISSUE TITLE
ModuleNotFoundError: No module named 'aimet_common.libpymo'

### ISSUE THREAD

**Issue by andrew8yang** [quic/aimet#2459]
branch: * develop

commit a3f3f3e35cbd6952407ec614a3b04faf714bf71f (HEAD -> develop, origin/develop, origin/HEAD)
Author: Joel Polizzi <quic_jpolizzi@quicinc.com>
Date:   Fri Aug 25 13:51:08 2023 -0700

python Examples/torch/compression/channel_pruning.py --dataset_dir mydatasetdir --use_cuda --epochs 15 --learning_rate 1e-2

it seems to there was no libpymo.py under directory  "aimet/TrainingExtensions/common/src/python/aimet_common/" , please help to check it . i am counting on you . thanks

**Comment by surajpandey353** [comment]
hi @andrew8yang,

Were you able to resolve this issue. I am facing same with latest 1.28.0 version. 

`
from aimet_torch.quantsim import QuantizationSimModel
File "anaconda3/envs/aimet/lib/python3.8/site-packages/aimet_torch/quantsim.py", line 53, in <module>
import aimet_common.libpymo as libpymo
ImportError: liblapacke.so.3: cannot open shared object file: No such file or directory
`

libpymo doesn't exit under anaconda3/envs/aimet/lib/python3.8/site-packages/aimet_torch. Rather there is this: anaconda3/envs/aimet/lib/python3.8/site-packages/aimet_common/libpymo.cpython-38-x86_64-linux-gnu.so

Thanks!

**Comment by Keywennn** [comment]
Have you resolved this issue?

**Comment by canyagmur** [comment]
Resolved the issue @[480](https://github.com/quic/aimet/issues/480#issuecomment-2092818665).
