### ISSUE TITLE
Version 1.28.0 installed failed.

### ISSUE THREAD

**Issue by xiaoniuba** [quic/aimet#2464]
Hi guys, when I run the command below following the guide [AIMET Installation and Setup](https://quic.github.io/aimet-pages/releases/1.28.0/install/install_host.html) :

> `python3 -m pip install ${download_url}/AimetOnnx-${AIMET_VARIANT}_${release_tag}-${wheel_file_suffix}`

, I got an ERROR: 

> `ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cpu (from aimetonnx) (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.9.1+cpu`

Any help will be appreciated.

**Comment by xiaoniuba** [comment]
Version 1.28.0 needs python3.8, and I have installed it, but why python3.9 is needed here.

**Comment by quic-mangal** [comment]
If you are trying to use ONNX, then PT 1.9 is needed. We don't support PT 1.13 for ONNX ATM. It will be available in subsequent releases.

**Comment by xiaoniuba** [comment]
I think the reason may be the required torch version is not available, which is **1.9.1+cpu**.

> ERROR: Could not find a version that satisfies the requirement torch==1.9.1+cpu (from aimetonnx) (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)

**Comment by quic-mangal** [comment]
Can you try installing it?

**Comment by xiaoniuba** [comment]
After I added "-f https://download.pytorch.org/whl/torch_stable.html" to the original command line, it worked. Thanks :)

**Comment by haithink** [comment]
> -f https://download.pytorch.org/whl/torch_stable.html"

Amazing!!!!!!!!!!!
