### ISSUE TITLE
How to specify start and end quant simulation node like pytorch QuantStub?

### ISSUE THREAD

**Issue by wendalegood** [quic/aimet#2466]
hi, I want to specify the start and end quant simulation node, I can do that by insert QuantStub with pytorch, but how to do this by aimet? Thanks

**Comment by quic-mangal** [comment]
You could disable the quantizers you don't want to quantize. This way you could quantize between two specific nodes only.

**Comment by wendalegood** [comment]
thanks for reply, but how to disable the specified quantizers

**Comment by wendalegood** [comment]
thanks for reply, but how to disable quantizers

**Comment by quic-mangal** [comment]
names_to_exclude = [] # You need to populate this
for name, module in quantized_model.named_modules():
    if isinstance(module, QcQuantizeWrapper):
        if name in names_to_exclude:
             #Disable all quantizers you would like to disable

**Comment by wendalegood** [comment]
ok, thanks
