### ISSUE TITLE
In QAT "is_symmetric"=True but "offset" is not 0 or -128 so that cannot snpe-onnx-to-dlc model

### ISSUE THREAD

**Issue by anxiang1836** [quic/aimet#2468]
I trained a model(Unet) by using QuantizationSimModel and export the encoding....

```
sim = QuantizationSimModel(model=model,
                               quant_scheme=QuantScheme.training_range_learning_with_tf_init,
                               dummy_input=dummy_input,
                               default_output_bw=8,
                               default_param_bw=8)
```

When I use snpe-onnx-to-dlc it raise Value Error:
`Invalid offset overridden for symmetric encodings got [-127], expected -128.`

How can I fix this problem？Can I simply change these layer "is_symmetric"=False？

The encoding is :
  "param_encodings": {
      "causal_unet.conv_block.0.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 3.755411386489868,
              "min": -3.7191641330718994,
              "offset": -127,
              "scale": 0.02931206086102654
          }
      ],
      "causal_unet.conv_block.0.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.2623538374900818,
              "min": -6.317215138551546e-06,
              "offset": 0,
              "scale": 0.001028863351785178
          }
      ],
      "causal_unet.conv_block.1.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.3879189193248749,
              "min": -0.3700578510761261,
              "offset": -124,
              "scale": 0.00297245792314118
          }
      ],
      "causal_unet.conv_block.1.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.3207032382488251,
              "min": -0.0591655857861042,
              "offset": -40,
              "scale": 0.0014896816628820757
          }
      ],
      "causal_unet.conv_block.2.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.451636403799057,
              "min": -0.5143707990646362,
              "offset": -136,
              "scale": 0.0037882635406419345
          }
      ],
      "causal_unet.conv_block.2.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.2641659080982208,
              "min": -0.014394105412065983,
              "offset": -13,
              "scale": 0.001092392209844262
          }
      ],
      "causal_unet.conv_block.3.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.24216043949127197,
              "min": -0.30536505579948425,
              "offset": -142,
              "scale": 0.002147158805061789
          }
      ],
      "causal_unet.conv_block.3.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.24552950263023376,
              "min": -5.478674211190082e-05,
              "offset": 0,
              "scale": 0.000963075644597434
          }
      ],
      "causal_unet.tran_conv_block.0.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.6038056015968323,
              "min": -0.6113137602806091,
              "offset": -128,
              "scale": 0.004765173968146829
          }
      ],
      "causal_unet.tran_conv_block.0.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.1924406737089157,
              "min": -0.16373410820960999,
              "offset": -117,
              "scale": 0.0013967638506608851
          }
      ],
      "causal_unet.tran_conv_block.1.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.9945582747459412,
              "min": -0.8437299728393555,
              "offset": -117,
              "scale": 0.00720897351994234
          }
      ],
      "causal_unet.tran_conv_block.1.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.20598334074020386,
              "min": -0.002424496691673994,
              "offset": -3,
              "scale": 0.0008172856369877563
          }
      ],
      "causal_unet.tran_conv_block.2.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.48943787813186646,
              "min": -0.379271537065506,
              "offset": -111,
              "scale": 0.0034067035890093036
          }
      ],
      "causal_unet.tran_conv_block.2.conv.2.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.3434898257255554,
              "min": -0.0014443508116528392,
              "offset": -1,
              "scale": 0.001352683045243954
          }
      ],
      "causal_unet.tran_conv_block.3.conv.0.weight": [
          {
              "bitwidth": 8,
              "dtype": "int",
              "is_symmetric": "True",
              "max": 0.006819768808782101,
              "min": -0.011531051248311996,
              "offset": -160,
              "scale": 7.196400022389842e-05
          }
      ]
  }

**Comment by quic-mangal** [comment]
@anxiang1836, yes, you can use the config_file option to modify the is_symmetric variable and set it to False

**Comment by anxiang1836** [comment]
> @anxiang1836, yes, you can use the config_file option to modify the is_symmetric variable and set it to False

Thanks...
I have noticed the option `config_file` in API `aimet_torch.quantsim.QuantizationSimModel`....I will try it layter..

**Comment by anxiang1836** [comment]
> @anxiang1836, yes, you can use the config_file option to modify the is_symmetric variable and set it to False

Thanks a lot……
That works. :)
