### ISSUE TITLE
The export model is  quantified model ?

### ISSUE THREAD

**Issue by wminiboy** [quic/aimet#2471]
quantsim = QuantizationSimModel(model=model, quant_scheme='tf_enhanced',
                                    dummy_input=dummy_input, rounding_mode='nearest',
                                    default_output_bw=8, default_param_bw=8, in_place=False)

    quantsim.compute_encodings(forward_pass_callback=partial(evaluator, use_cuda=use_cuda),
                               forward_pass_callback_args=iterations)

    quantsim.export(path=logdir, filename_prefix='resnet_encodings', dummy_input=dummy_input.cpu())
    accuracy = evaluator(quantsim.model, use_cuda=use_cuda)

    When executing the above code ，the result resnet_encodings.onnx in not a quantified model .  because the size is not decreased, but why the  after log show  "  logger.info("Quantized Model top-1 accuracy = %.2f", accuracy)"  is quantized model accuracy.

**Comment by quic-mangal** [comment]
@wminiboy, we are simulating the behavior of quantization, where in when data passes through the model, there will be quantization and dequantization and resulting output will have quantization noise. 
When we export, we export a FP32 model along with an encodings file which can be taken to target, loaded back into the model etc

**Comment by wminiboy** [comment]
@quic-mangal  Thank you !
