### ISSUE TITLE
[Question] Static and Dynamic Quantization using AIMET

### ISSUE THREAD

**Issue by balaabhijit** [quic/aimet#2477]
Hey Aimet team! Thank you so much for this wonderful work!

I have been playing around with AIMET and I have a few questions.

## Experiment 1: Assuming Dynamic Quantization.
I am assuming this is `dynamic` quantization: Where the weight's rmin/rmax are fixed already but the activation's rmin/rmax is dynamically computed for each batch. I deliberately avoid calling `sim.compute_encodings()` here 
```python
dummy_input = torch.rand(5, 3, 224, 224)
logger.info("Creating a Quantization simulation model")
simulation = QuantizationSimModel(
    model=model,
    dummy_input=dummy_input,
    default_output_bw=16,
    default_param_bw=8,
)
logger.info(f"Model After Quantization using AIMET")
logger.info(simulation.model)
# I deliberately do not call the sim.compute_encodings(...)
# Assuming the rmin/rmax for activations are dynamic/changing for each batch since we didn't do any calibrations.
evaluate(simulation.model, val_data_loader=val_data_loader, use_cuda=use_cuda)
```

## Experiment 2: Assuming Static Quantization
I am assuming this is static quantization where after the calibration (compute_encodings()), rmin/rmax of the activations are fixed and do **NOT** change during evaluation.
```python
dummy_input = torch.rand(5, 3, 224, 224)
logger.info("Creating a Quantization simulation model")
simulation = QuantizationSimModel(
    model=model,
    dummy_input=dummy_input,
    default_output_bw=16,
    default_param_bw=8,
)
logger.info(f"Model After Quantization using AIMET")
logger.info(simulation.model)

logger.info("Computing Encodings (Calibration)")
# Assuming this fixes the rmin/rmax at the end of calibration
simulation.compute_encodings(
    forward_pass_callback=forward_pass_callback,
    forward_pass_callback_args=calibration_data_loader,
)

# Assuming the rmin/rmax for activations are static (They do not change) for each batch since we did a calibration run.
evaluate(simulation.model, val_data_loader=val_data_loader, use_cuda=use_cuda)
```

## Results
For `Resnet50` using `PyTorch`.
**Exp 1: Dynamic quantization**: top1_accuracy: 76.1365, top5_accuracy: 92.830668
**Exp 2: Static quantization**: top1_accuracy: 75.90113, top5_accuracy: 92.723

As you can see **Experiment 1 (my assumption of dynamic quantization) has a slightly better performance**

## Question
Are my assumptions about static and dynamic quantization using the `aimet` framework right? If not how would I go about doing static/dynamic quantization using the framework? 

Thanks in advance!

**Comment by quic-mangal** [comment]
In the first case, we only collect statistics for Activations, we don't quantize dequantize it. In the second case we do both for activations. So that is why your accuracy is better in the 1st case. 
Also, AIMET only supports the static mode, so 2nd piece of code is the correct workflow.

**Comment by balaabhijit** [comment]
Thanks a lot for the quick reply!

**Comment by balaabhijit** [comment]
So if I understand this right I would expect the first case's result and the FP32 precision to match but that doesn't seem to be the case. The first case's result is slightly less than the original FP32 accuracy. Do you have any idea why it is? 

`The original FP32 accuracy which I got was: Top1: 76.32643, Top5: 92.945902`

**Comment by quic-mangal** [comment]
Weights get quantized in both cases

**Comment by balaabhijit** [comment]
Thanks!
