### ISSUE TITLE
.tar file mentioned in aimet/packaging/INSTALL.txt is not found!

### ISSUE THREAD

**Issue by marjanemd** [quic/aimet#25]
Trying to install aimet, followinf the install.txt instructions, but could not find the following .tar file:

aimet-release-1.7.0_build-<VERSION>.tar.gz

**Comment by quic-akhobare** [comment]
Thanks @marjanemd for pointing this out. It turns out that the INSTALL.txt is outdated. The install instructions are in the USAGE.md. We will clean out the outdated instructions.
