### ISSUE TITLE
Does support HuggingFace Accelerate?

### ISSUE THREAD

**Issue by emphasis10** [quic/aimet#2562]
Hello. I'm trying to do QAT method with aimet module at Huggingface [Llama](https://huggingface.co/docs/transformers/main/model_doc/llama) model. Here's some question during tests.

As you know, llama models are pretty huge, so I tried to train model with multi-node GPUs. Especially I used Accelerate from HuggingFace. It seems to be working fine, but I found one issue. Comparing to original model(w.o. QAT), required training time for QAT model was drastically longer. I tracked GPU utilization and power consumption by watching `nvidia-smi`, it consumed almost maximum power very shortly and for remained time, consumed comparative lower power. To sum up, I think there are some bottleneck in the training loop. 

I wonder if those bottlenecks are caused by compatibility between the accelerate module and the aimet module or by the addition of simulation operation.

Thank you for all in advance :)

**Comment by quic-mangal** [comment]
The addition of simulation operators does add time for QAT..

**Comment by emphasis10** [comment]
> The addition of simulation operators does add time for QAT..

Don't simulation operators support GPU acceleration? I expected some time increase, but I didn't know it would increase to several times the time.

**Comment by quic-mangal** [comment]
They do support GPU acceleration. Is the GPU usage high or low when training?

**Comment by emphasis10** [comment]
@quic-mangal GPU utilization is around 90%. But most of the time it consumes about 100W of power and only for a short time it consumes around 300W of power(I'm using the Nvidia A100 GPU). This is in contrast to when learning without QAT, where it consumes more than 300W of power most of the time.

**Comment by quic-kyunggeu** [comment]
Hi @emphasis10, thanks for filing this issue.

I think it would be more helpful for our understanding if you provide more details and quantities.
In general, it is normal that QAT is slower than FP (i.e. non-QAT) training. It would all depend on how slower it is to really tell if there's anything wrong. The speed will also depend much on the distributed training backend of accelerate.

Orthogonally, however, one thing you might want to check is the `quant_scheme` argument of QuantizationSimModel. If you're passing `quant_scheme=QuantScheme.post_training_tf` or `quant_scheme=QuantScheme.post_training_tf_enhanced` (**default**) to the constructor of `QuantizationSimModel`, it's going to be very unsuitable for QAT for a few reasons, one of them being that QAT is too slow (at least 10x for LLMs) compared to FP training. **NOTE that this is the case if you're not explicitly passing `quant_scheme`.**

 I'd suggest passing either `quant_scheme=QuantScheme.training_range_learning_with_tf_init` or `quant_scheme=QuantScheme.training_range_learning_with_tf_enhanced_init`. I expect QAT will be only <2x slower than FP training with these arguments.

**Comment by emphasis10** [comment]
Hello, @quic-kyunggeu ! First of all, I really appreciate for replying me :)

Yes. I was using the default quantization scheme, so I tried both of what you recommended. Second one didn't seem to work for me, while first one cut the time in half. So, is there no performance drop as I change the scheme?

Thank you, again :+1:

**Comment by quic-mangal** [comment]
With TF scheme you can expect slight drop, but it won't be significant as you are performing training. 

What is the issue that you see with second suggestion?

**Comment by emphasis10** [comment]
@quic-mangal Hello. Thanks for replying. For me, there's no difference in training time with second suggetion compared to `QuantScheme.post_training_tf_enhanced` scheme.

**Comment by quic-kyunggeu** [comment]
@emphasis10  It might be the case that you are confusing `compute_encodings()` with training.
`compute_encodings()` (also called "encoding calibration" in some context) is just a statistical process to observe the inputs and outputs of quantizers and initialize the corresponding quantization parameters accordingly. In AIMET, we don't call this "training" since there is no gradient computation involved in this process.
That being said, `QuantScheme.training_*` are **faster and provides better accuracy** than `QuantScheme.post_training_*` during training, and `QuantScheme.*_tf` are is **faster but provides worse accuracy** than `QuantScheme.*_tf_enhanced` during `compute_enconding()`.

**Comment by emphasis10** [comment]
@quic-kyunggeu WOW!!!! What a clear answer! Thanks for you explanation. Yes, I think I was completely confused like you said. To sum up, If I'm going to additional **train** with some dataset and accuracy is all I care about, I should use `QuantScheme.training_range_learning_with_tf_enhanced_init` even though it will take more time than other remained, right?

**Comment by quic-mangal** [comment]
When you use training_range_learning_with_tf_enhanced_init only compute encodings part will take more time. Training part should be the same for training_range_learning_with_tf_enhanced_init and training_range_learning_with_tf_init

**Comment by emphasis10** [comment]
@quic-mangal Okay. Thanks for making it clear. Have a nice day!
