### ISSUE TITLE
Unable to start docker container from codelinaro artifact

### ISSUE THREAD

**Issue by vismaysur** [quic/aimet#2594]
Hi, when I try to install AIMET in Docker following the steps outlined [here](https://quic.github.io/aimet-pages/releases/latest/install/install_docker.html), a SSL/TLS certificate error is returned.

```
Unable to find image 'artifacts.codelinaro.org/codelinaro-aimet/aimet-dev:latest.onnx-gpu' locally
docker: Error response from daemon: Get "https://artifacts.codelinaro.org/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority.
```

Kindly address the same. Thank you in advance for the help!

**Comment by quic-jpolizzi** [comment]
Hi @Vismay-dev Please try again, Code Linaro updated their certs last week and there was an issue, they fixed it as of this past Friday. Please try again and let me know if the issue is resolved on your end.

**Comment by vismaysur** [comment]
Hey @quic-jpolizzi. Yes, the issue has been resolved on my end. Thank you!
