### ISSUE TITLE
Deprecation warning after pip install AIMET 1.30 torch gpu

### ISSUE THREAD

**Issue by escorciav** [quic/aimet#2657]
I'm getting the following deprecation warning while following the installation steps [here](https://github.com/quic/aimet/blob/release-aimet-1.24/packaging/install.md#install-aimet-packages)
```bash
pip install https://github.com/quic/aimet/releases/download/1.30.0/Aimet-torch_gpu_1.30.0-cp38-cp38-linux_x86_64.whl
Collecting Aimet==torch-gpu-1.30.0
  Downloading https://github.com/quic/aimet/releases/download/1.30.0/Aimet-torch_gpu_1.30.0-cp38-cp38-linux_x86_64.whl (6.7 kB)
DEPRECATION: aimet torch-gpu-1.30.0 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of aimet or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
```

Details of my environment:
```bash
conda create --name hello_aimet python=3.8
conda activate hello_aimet 
pip install --extra-index-url https://download.pytorch.org/whl/cu118 -r requirements_aimet.txt
pip install https://github.com/quic/aimet/releases/download/1.30.0/Aimet-torch_gpu_1.30.0-cp38-cp38-linux_x86_64.whl
```

Any hint?
[requirements_aimet.txt](https://github.com/quic/aimet/files/14026649/requirements_aimet.txt)

**Comment by quic-hitameht** [comment]
tagging @quic-bharathr here.

**Comment by escorciav** [comment]
I fixed so closing.

I managed to create a conda+pip environment and add aimet_torch to it.

_What's the crack?_
I think using the precise version of: Python, PyTorch, and Cuda (if pertinent). I went with pip binaries. It would be great if the team mentions if they use PyPi, anaconda or built PyTorch from scratch :wink:
