### ISSUE TITLE
Can I run the A16W8 model with a Qualcomm chip dsp?

### ISSUE THREAD

**Issue by ZengZhiK** [quic/aimet#2711]
Hi!

I have a model that uses Aimet quantization, the weights are 8-bit quantization and the activation layer is 16-bit quantization.

The following is the output of the `snpe-dlc-info` command:
![image](https://github.com/quic/aimet/assets/47879928/9e01a85a-12a6-4b7f-ac82-fe73295829b3)

I ran this model on a Qualcomm 6490 chip, using the following command:

```shell
snpe-net-run --container model.dlc \
--input_list test_raw_list.txt \
--output_dir snpe_output_test_quantized

snpe-net-run --container model.dlc \
--input_list test_raw_list.txt \
--output_dir snpe_output_test_quantized_dsp \
--use_dsp
```

But when I add the `--use_dsp` parameter, the result gets worse.

Is it because the dsp can only run purely 8bit quantized models?

I see that many people have asked this question, but there is no solution. Do you have a solution now?

‒ https://developer.qualcomm.com/forum/qdn-forums/software/qualcomm-neural-processing-sdk/703
‒ https://developer.qualcomm.com/forum/qdn-forums/software/qualcomm-neural-processing-sdk/69900
‒ https://developer.qualcomm.com/forum/qdn-forums/software/qualcomm-neural-processing-sdk/70529
‒ https://github.com/quic/aimet/issues/1883
‒ https://github.com/quic/aimet/issues/2197
‒ https://github.com/quic/aimet/issues/1303

Thanks!

**Comment by ZengZhiK** [comment]
I I found that the latest SNPE 2.20 fixes this bug

**Comment by zengjie617789** [comment]
how to make a A16W8 model? I test on snpe-pytorch-dlc with encoding params, but it seems not work.
