### ISSUE TITLE
Unable to install AIMET using docker and Colab also

### ISSUE THREAD

**Issue by Santoshkumar14** [quic/aimet#275]
Hello sir,
I have gone through the installation guide of AIMET of DOCKER (https://github.com/quic/aimet/blob/develop/packaging/docker_install.md#setup-the-environment) as well as COLAB(https://github.com/quic/aimet/blob/develop/packaging/google_colab_install.md). 
Both of them gave me errors as Docker gives:-
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
CMake Error at CMakeLists.txt:70 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

and Colab gives:-

CMake Deprecation Warning at CMakeLists.txt:72 (cmake_policy):
  The OLD behavior for policy CMP0022 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:77 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:82 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy.distutils

what should I do?

**Comment by quic-akhobare** [comment]
Sorry for the late response. Can you share your version of cmake please?

**Comment by quic-akhobare** [comment]
@quic-bharathr - tagging you so you can monitor this

**Comment by adityakoolkarni** [comment]
@Santoshkumar14  I actually built a docker image using the dockerfile given in the aimet reposotiry [(here)](https://github.com/quic/aimet/blob/develop/Jenkins/Dockerfile). The image can be found [here](https://hub.docker.com/r/adityakoolkarni/aimet-docker). You can then launch a container using the image use 'docker run ' command. Then run the two lines of environment setup commands given in the documentation [here](https://github.com/quic/aimet/blob/develop/packaging/docker_install.md#setup-paths).

**Comment by adityakoolkarni** [comment]
@quic-ssiddego  I'm also facing issues in setting up the colab notebook. I'm following the same instructions given in the documentation. There is a conflict in getting dependencies satisfied with scikit-learn. I have attached the file [scikit_build_issue_colab.txt](https://github.com/quic/aimet/files/6058053/scikit_build_issue_colab.txt). Changing the scikit-learn requirement from "scikit-learn==0.19.1" to "scikit-learn" helped with this issue. But then found another conflict in "libpymo package". 


![image](https://user-images.githubusercontent.com/53965740/109434559-ba3f5700-79ca-11eb-9718-f262d855c6e2.png)

**Comment by quic-akhobare** [comment]
@adityakoolkarni - that just means that you don't have the path to libpymo set in PYTHONPATH env variable
Either do this 
`
sys.path.append('/usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu')
`
or append '/usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu' to your PYTHONPATH. Note I am assuming that that is the path to aimet_common in your installation. So check that.

This is in the install instructions. If something is not clear there, please update the instructions via a PR.

**Comment by quic-akhobare** [comment]
By the way, I am not sure if both of you @adityakoolkarni  and @Santoshkumar14 have looked at the Google Colab install instructions here.. If you want to install and use AIMET
https://github.com/quic/aimet/blob/develop/packaging/google_colab_install.md

For AIMET developers there are separate instructions in the same folder.

**Comment by adityakoolkarni** [comment]
> @adityakoolkarni - that just means that you don't have the path to libpymo set in PYTHONPATH env variable
> Either do this
> `sys.path.append('/usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu')`
> or append '/usr/local/lib/python3.6/dist-packages/aimet_common/x86_64-linux-gnu' to your PYTHONPATH. Note I am assuming that that is the path to aimet_common in your installation. So check that.
> 
> This is in the install instructions. If something is not clear there, please update the instructions via a PR.

@quic-akhobare thanks for your reply. I had included the environment setup details. On checking the contents of the path I find that the packages are installed in python3.7 instead of python3.6(expected path). I'll check on this and revert back.


Edit: I tried to resolve the issue but may be I'm missing some setting here. I just ran the installing google colab instruction notebook that was provided in the documentation, but I'm seeing same issue [Colab Notebbook](https://colab.research.google.com/drive/1fn-TspQkAmeGaHK2a0Ah9zZy-NCsbDFb?usp=sharing). Any pointers would be very helpful. Prior to this I have been using the setup with docker version that did not have any issues.

**Comment by quic-akhobare** [comment]
> On checking the contents of the path I find that the packages are installed in python3.7 instead of python3.6(expected path).

It's unusual to have an environment with two different version of python installed? Can you please explain your environment? Did you intend to install python 3.7 and also python 3.6?

**Comment by adityakoolkarni** [comment]
> 
> 
> > On checking the contents of the path I find that the packages are installed in python3.7 instead of python3.6(expected path).
> 
> It's unusual to have an environment with two different version of python installed? Can you please explain your environment? Did you intend to install python 3.7 and also python 3.6?

By default google colab launched with the following (as shown in pic) configuration for Python. The packages are not getting installed in Python 3.6 path but instead in Python 3.7 (second image), possibly the reason why scikit-learn dependencies are also not being met. 

![image](https://user-images.githubusercontent.com/53965740/109464393-758fdc00-7a1b-11eb-963d-db7a8c27d24b.png)

This is strange because when I compared with the installation logs visible in the AIMET example its getting installed in Python 3.6. Possibly there is some setting in Colab I'm not sure about this though.

![image](https://user-images.githubusercontent.com/53965740/109465348-e5eb2d00-7a1c-11eb-9e01-9d6eb0372777.png)

**Comment by nsping13** [comment]
following

**Comment by nsping13** [comment]
hi, any solution for that? 
thanks a lot

**Comment by nsping13** [comment]
@quic-akhobare apparently there is no option to work with python 3.6 in google collab as is, just in local mode. Can you maybe update the code so that it work with google collab 3.7 as well
thanks a lot

**Comment by quic-ssiddego** [comment]
Hi @nsping13  Thank you for reporting this. We are looking into addressing this issue. Please track this issue for a resolution https://github.com/quic/aimet/issues/496.

**Comment by quic-bharathr** [comment]
@nsping13 We're working on python 3.7 support to re-enable the use of AIMET with Google Colab. ETA is the week of May 3.

**Comment by quic-akhobare** [comment]
No update in a while.
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
