### ISSUE TITLE
import Error： cannot import name 'apply_adaround_te' from 'aimet_torch.quantsim'

### ISSUE THREAD

**Issue by 1826133674** [quic/aimet#2909]
I am using AIMET for the quantification of Stable-diffusion v1-5 according to the guidance in the following link 

`https://docs.qualcomm.com/bundle/publicresource/topics/80-64748-1/model_updates.html.`

 However, during the process of PTQ quantification, I encountered the following error:

`ImportError: cannot import name 'apply_adaround_te' from 'aimet_torch.quantsim'`

The AIMET version I am using is as follows:
 ` aimet_torch torch-gpu-1.31.0 `

It is downloaded from the following link：
` https://github.com/quic/aimet/releases/download/1.31.0/aimet_torch-torch_gpu_1.31.0-cp38-cp38-linux_x86_64.whl`

I followed the instructions in the following file to build docker, and then installed the wheel package in it,

` https://github.com/quic/aimet/blob/develop/Jenkins/Dockerfile.torch-gpu`

Please help me point out what changes I should make to solve this problem, thank you very much!

**Comment by quic-hitameht** [comment]
@1826133674 Have you downloaded the folder containing jupyter notebook? Please follow this guide: https://docs.qualcomm.com/bundle/publicresource/topics/80-64748-1/introduction.html 

Once you have built AIMET docker and downloaded the required folder, you will need to run `launch.sh` script which will install additional dependencies and start the jupyter server then you should be able to run `stable_diffusion.ipynb`

Let me know if you have any other questions.

**Comment by 1826133674** [comment]
Thank you for your reply! I'v got the apis in the zip files.
