### ISSUE TITLE
Can I use AIMET to quantize my PyTorch model and convert it to a TFLite model?

### ISSUE THREAD

**Issue by zhuoran-guo** [quic/aimet#3073]
@quic-mangal @quic-akhobare 
Hello, I want to know if I can use the AIMET tool to quantize my PyTorch model and convert it to a TFLite model. I have a model trained using PyTorch and want to deploy it on a device as a TFLite model. Can I use AIMET for the quantization?

There are two methods to do it:

PyTorch model → AIMET (torch quantization) → ONNX + encoding file → TensorFlow → TFLite
PyTorch model → TensorFlow → AIMET (TensorFlow quantization) → regular TF meta/checkpoint model → TFLite

For method 1, do you provide an API to convert the ONNX model and encoding file to a TensorFlow model?
And is it possible to use method 2 to do the process?

Thank you so much

**Comment by quic-akhobare** [comment]
Hi @zhuoran-guo 
Excellent question. It just so happens that the Qualcomm AI Hub (https://aihub.qualcomm.com/) does follow method 1.

They do have some documentation on this here: https://app.aihub.qualcomm.com/docs/hub/compile_examples.html#compiling-models-quantized-with-aimet-to-tflite-or-qnn

Hope that helps. I will close this. Please reopen if needed.

**Comment by zhuoran-guo** [comment]
@quic-akhobare 
thanks for your response !
YES, Qualcomm AI Hub can do it follow method 1 , it help me a lot 
but it shows this api return the results as [CompileJob](https://app.aihub.qualcomm.com/docs/hub/generated/qai_hub.CompileJob.html#qai_hub.CompileJob)
And I want to know is that possible to save the .tflite model local? 
```
compile_job = hub.submit_compile_job(
    model="mobilenet_v2.pt",
    device=hub.Device("Samsung Galaxy S23 (Family)"),
    input_specs=dict(image=(1, 3, 224, 224)),
)
```
