### ISSUE TITLE
Add working example for quantized evaluation of a PyTorch resnet18 model

### ISSUE THREAD

**Issue by quic-akhobare** [quic/aimet#342]
- Create a new examples directory at the top-level
- Use the API doc examples to use the QuantizationSimModel API to achieve a quantization sim evaluation for a torchvision resnet18 model

If you are interested in working on this issue - please indicate via a comment on this issue. It should be possible for us to pair you up with an existing contributor to help you get started. 

From a complexity perspective, this ticket is at an easy level.

**Comment by mohanksriram** [comment]
Hi, I'm interested in working on this issue. Please let me know how I could start.

**Comment by quic-ssiddego** [comment]
Hi @mohanksriram Thank you for your interest in contributing to AIMET. This issue is currently being worked on by the team. Would you be interested in contributing to other topics? Please check #673 #674 and #672 and let us know. Look forward to your contribution.

**Comment by quic-akhobare** [comment]
There is an existing example now. Closing the ticket.
