### ISSUE TITLE
Add working example for QAT of a PyTorch resnet18 model

### ISSUE THREAD

**Issue by quic-akhobare** [quic/aimet#343]
Create a new examples directory at the top-level
Use the API doc examples to use the QuantizationSimModel API to achieve quantization aware training for a torchvision resnet18 model
If you are interested in working on this issue - please indicate via a comment on this issue. It should be possible for us to pair you up with an existing contributor to help you get started.

From a complexity perspective, this ticket is at an easy level.

**Comment by ibei** [comment]
any example now?

**Comment by Rohan-Chaudhury** [comment]
Hi,
Could you please help to verify the example code for QAT of a PyTorch resnet18 model that I have added?

Thanks & Regards,
Rohan

**Comment by quic-akhobare** [comment]
There is an existing example now. Closing the ticket.
