### ISSUE TITLE
Add working example for compressing a PyTorch resnet18 model using Spatial SVD

### ISSUE THREAD

**Issue by quic-akhobare** [quic/aimet#344]
- Create a new examples directory at the top-level
- Use the API doc examples to apply Spatial SVD model compression to a PyTorch resnet18 model

If you are interested in working on this issue - please indicate via a comment on this issue. It should be possible for us to pair you up with an existing contributor to help you get started.

From a complexity perspective, this ticket is at an easy level.

**Comment by adityakoolkarni** [comment]
@quic-akhobare, I'm interested in working on this.

**Comment by quic-akhobare** [comment]
Sorry for the late response @adityakoolkarni
Great to hear that you would like to work on this. Please go ahead. 
@quic-mangal please help @adityakoolkarni if he needs guidance. We don't yet have a top-level examples folder. Please create that and add this example under that.

**Comment by adityakoolkarni** [comment]
@quic-mangal Are there any results/ guidelines in choosing the size of subset of validation that's optimal to perform evaluation the SVD compression during the greedy search optimization? I saw in one of the video tutorial that just 2K images were used.

**Comment by quic-mangal** [comment]
Hi @adityakoolkarni, the 2000 image set was derived from the ImageNet dataset itself, where 2 images were picked randomly for each class. For choosing a validation dataset, we want to make sure each of the classes is represented, therefore, choosing 2K images would be a good sample for validation.

**Comment by quic-ssiddego** [comment]
Hi @adityakoolkarni Just wanted to follow-up on this. Do you have any code ready that needs a review or have further questions for us at this time? Please let us know if you need help. Look forward to your contribution to AIMET. Thank you

**Comment by adityakoolkarni** [comment]
I have a working code for this but its a .py file. I think Colab would be very appropriate for a tutorial. So I'm hoping of pushing this as a Colab notebook, but I'm stuck in that part due to Colab issues #496.

**Comment by quic-ssiddego** [comment]
Thank you for the update @adityakoolkarni . @quic-bharathr - Is there an ETA on the fix for #496?

**Comment by quic-ssiddego** [comment]
@adityakoolkarni Just wanted to check with you : while we await a fix for this issue - would you be interested in exploring alternate ways to push your updates - using a jupyter notebook or such. Please share your thoughts.

**Comment by quic-akhobare** [comment]
There is an existing example now. Closing the ticket.
