### ISSUE TITLE
How to find aimet_torch.pro

### ISSUE THREAD

**Issue by songh11** [quic/aimet#3485]
I use this to install aimet-torch, but I can't import aimet_torch.pro. How can I install it?
```shell
apt-get install liblapacke
python3 -m pip install aimet-torch
```

**Comment by jacobroedel-dell** [comment]
@songh11 Where did you find the pro module?

**Comment by IbarakiRino** [comment]
AFAIK, aimet_torch.pro has been deprecated now. 
Perhaps you can try downloading AIMETPro from [QPM](https://qpm.qualcomm.com/#/main/tools/details/Qualcomm_AIMET_Pro). I tested 1.34.0 version and it works, hope it helps you ;-)
