### ISSUE TITLE
1.35 in QSC but not here?

### ISSUE THREAD

**Issue by NikilXYZ** [quic/aimet#3539]
I see version 1.35 released on Nov 12 in the Qualcomm Software Center and Qualcomm Package Manager (which don't work properly on my computer btw), but I don't see it here or on PyPI.

Can you please update the releases here and on PyPI?

**Comment by quic-hitameht** [comment]
Hi @NikilXYZ Sorry for delayed response. AIMET 1.35 is now available both here and on PyPI.

**Comment by NikilXYZ** [comment]
Thanks. I've updated accordingly. Can you also tell me why the ONNX version uses a different version of CUDA than the default AIMET?
