### ISSUE TITLE
AimetTensorQuantizer argument error during testing example code.

### ISSUE THREAD

**Issue by ibei** [quic/aimet#358]
To reproduce:

****************************************************************
import torch 
from torchvision import models
from aimet_torch.quantsim import QuantizationSimModel

BATCH_SIZE = 1
input_shape = (BATCH_SIZE, 3, 224, 224)

model = models.resnet18(pretrained=True).cuda()

sim = QuantizationSimModel(model, default_output_bw=8, default_param_bw=8, input_shapes=input_shape)

****************************************************************

the error is,

Traceback (most recent call last):
  File "Docs/torch_code_examples/test.py", line 12, in <module>
    sim = QuantizationSimModel(model, default_output_bw=8, default_param_bw=8, input_shapes=input_shape)
  File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 165, in __init__
    self._add_quantization_wrappers(self.model)
  File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 508, in _add_quantization_wrappers
    quantized_module = self._create_quantizer_module(module_ref)
  File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 489, in _create_quantizer_module
    self._rounding_mode, self._quant_scheme)
  File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 295, in __init__
    is_output_quantized, is_symmetric)
  File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 211, in __init__
    enabled_by_default=is_output_quantized)]
  File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 99, in tensor_quantizer_factory
    enabled_by_default)
  File "/home/build/staging/universal/lib/python/aimet_torch/tensor_quantizer.py", line 107, in __init__
    self._cppOp = AimetTensorQuantizer.AimetTensorQuantizer(quant_scheme)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. AimetTensorQuantizer.AimetTensorQuantizer(arg0: DlQuantization::QuantizationMode)

Invoked with: <QuantizationMode.QUANTIZATION_TF_ENHANCED: 1>

************************************************************************

Anyone can solve this problem?

**Comment by ibei** [comment]
@quic-akhobare

**Comment by ibei** [comment]
anyone know how to solve this problem?

**Comment by ibei** [comment]
@quic-akhobare have you met this problem? Any suggestion? Thanks.

**Comment by ibei** [comment]
@quic-akhobare we checked the details and found that it seems to be a mismatch between 'libpymo.QUANTIZATION_TF' and 'DlQuantization::QuantizationMode'. But we do not know how to solve it.

**Comment by ibei** [comment]
@quic-bharathr  Any suggestion?

**Comment by quic-ssiddego** [comment]
Hi @ibei 

Sorry about the delay in response to this query.
Do you still see this issue? I tried the snippet provided and it seems to work as expected.
Could you please try without the .cuda() and let us know?

Thanks,
Sangeetha

**Comment by karljang** [comment]
Just for the record, it happened when I use LLVM compilers.

**Comment by jimmysue** [comment]
> To reproduce:
> 
> import torch
> from torchvision import models
> from aimet_torch.quantsim import QuantizationSimModel
> 
> BATCH_SIZE = 1
> input_shape = (BATCH_SIZE, 3, 224, 224)
> 
> model = models.resnet18(pretrained=True).cuda()
> 
> sim = QuantizationSimModel(model, default_output_bw=8, default_param_bw=8, input_shapes=input_shape)
> 
> the error is,
> 
> Traceback (most recent call last):
> File "Docs/torch_code_examples/test.py", line 12, in
> sim = QuantizationSimModel(model, default_output_bw=8, default_param_bw=8, input_shapes=input_shape)
> File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 165, in **init**
> self._add_quantization_wrappers(self.model)
> File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 508, in _add_quantization_wrappers
> quantized_module = self._create_quantizer_module(module_ref)
> File "/home/build/staging/universal/lib/python/aimet_torch/quantsim.py", line 489, in _create_quantizer_module
> self._rounding_mode, self._quant_scheme)
> File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 295, in **init**
> is_output_quantized, is_symmetric)
> File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 211, in **init**
> enabled_by_default=is_output_quantized)]
> File "/home/build/staging/universal/lib/python/aimet_torch/qc_quantize_op.py", line 99, in tensor_quantizer_factory
> enabled_by_default)
> File "/home/build/staging/universal/lib/python/aimet_torch/tensor_quantizer.py", line 107, in **init**
> self._cppOp = AimetTensorQuantizer.AimetTensorQuantizer(quant_scheme)
> TypeError: **init**(): incompatible constructor arguments. The following argument types are supported:
> 1. AimetTensorQuantizer.AimetTensorQuantizer(arg0: DlQuantization::QuantizationMode)
> 
> Invoked with: <QuantizationMode.QUANTIZATION_TF_ENHANCED: 1>
> 
> Anyone can solve this problem?

Any progress on this issue ?

**Comment by benv2k6** [comment]
We are having the same issue, compiled from source for python 3.8

**Comment by quic-akhobare** [comment]
We have moved to Python 3.8 and the pybind11 version mismatch is now avoided by using the same pybind for PyTorch and for AIMET.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
