### ISSUE TITLE
is there any example of modifying config_file(the .json file) while quantizing a new model

### ISSUE THREAD

**Issue by ibei** [quic/aimet#361]
there is a default config_file in the document. But I do not know how to modify it when I want to  quantize a new model. I think the setting in the default config_file should not be suitable for the new model. Am I wrong?

**Comment by quic-ssiddego** [comment]
> there is a default config_file in the document. But I do not know how to modify it when I want to quantize a new model. I think the setting in the default config_file should not be suitable for the new model. Am I wrong?

**Comment by quic-ssiddego** [comment]
Hi @ibei,

The config files are not model specific. They are designed to work for a specific runtime.
The default_config file provided is suitable for wide range of runtimes. But, if you need to edit the configuration for some reason, the details of the format are available here : https://quic.github.io/aimet-pages/AimetDocs/user_guide/quantization_sim.html#placement-of-quantization-simulation-ops-in-the-model

Please do let us know if you have further questions.

Thanks,
Sangeetha

**Comment by quic-akhobare** [comment]
No update in a while.
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
