### ISSUE TITLE
is that possible to add new quantization algorithm to AIMET by ourselves?

### ISSUE THREAD

**Issue by ibei** [quic/aimet#387]
We want to add our new algorithm to aimet.
how can we achieve this?

**Comment by quic-akhobare** [comment]
Hi @ibei 

Sorry for the late response. We would love to see new algorithms contributed to AIMET. Could you create an issue where you explain

- what is the problem being solved
- some details of the algorithm (link to papers if any etc.)

After we take a look through that we should be able to guide you a bit on how best to add this to AIMET so it can fit in nicely with the other techniques. We can have one existing AIMET contributor pair up with you to guide you on things like coding guidelines etc. Other than that, we work in continuous integration mode, so you and whoever else will contribute to this can just issue pull requests that one or more contributors can review and accept.

Looking forward to it. Lets get started.

**Comment by quic-akhobare** [comment]
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
