### ISSUE TITLE
Can we install AIMET on an AMD based machine?

### ISSUE THREAD

**Issue by akssieg** [quic/aimet#389]
I read the requirements as mentioned in the link [https://github.com/quic/aimet/blob/develop/packaging/docker_install.md](url) and intel cpu is recommended. Can this library be installed on a cpu based on AMD such as AMD Ryzen 9 3900X 12x 3.80GHz with GeForce RTX 2080 Ti.

**Comment by quic-ssiddego** [comment]
Hi @akssieg  Thank you for your query. As far as we know, it should work on AMD or other x86 CPUs including the one you mentioned above though we have only tested on machines with Intel CPUs. Please do let us know if you have further questions.
