### ISSUE TITLE
compute scalingMatrix23

### ISSUE THREAD

**Issue by Tiantian-Han** [quic/aimet#39]
file: ModelOptimizations/DlEqualization/src/ScaleFactorCalculator.cpp:
According to the equation on line 102, the calculation on line 132 should be:
reScalingMats->scalingMatrix23.at<float>(s) = (cubeRootMat.at<float>(s)) * (1.0f / rangeVec2.at<float>(s));
???

**Comment by quic-akhobare** [comment]
@quic-ssiddego, could you please check this?

**Comment by quic-mangal** [comment]
The comments need to be updated on line 102 ans 103 but the equations are right.

**Comment by quic-akhobare** [comment]
@quic-mangal, thanks for checking. Please fix the comment :)
