### ISSUE TITLE
About quantization algorithm supporting

### ISSUE THREAD

**Issue by zl-hw** [quic/aimet#395]
Hi，I saw tensorflow quantization code in quantsim.py ,  it seems there are other quantization methods,  called training_range_learning_with_tf_init or training_range_learning_with_tf_enhanced_init,  but finally they all map to QUANTIZATION_TF  or QUANTIZATION_TF_ENHANCED method the same as post traing .

What dose these code mean？Does AIMET have plan to support QAT algorithms that have trainable quantization paremeters, such as LSQ+？

Thanks！

**Comment by quic-akhobare** [comment]
Hi @zl-hw.. Sorry for the late response. Yes you are right that the idea was to support trainable quantization parameters in the future but we just have not gotten a chance to get to that yet.

**Comment by sohils** [comment]
I see the same in pytorch as well. Could you confirm the same for PyTorch?

**Comment by quic-akhobare** [comment]
Trainable quantization parameters are now supported.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
