### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by SEETHAMRAJU** [quic/aimet#40]
I used the buildandtest docker file. After it gave an interactive terminal i tried importing aimet packages but that didn't work. It threw an import error. I hope I followed the right steps. Please help me with this.

**Comment by quic-ssiddego** [comment]
Thanks for the report @SEETHAMRAJU. Could you please post the error message?

**Comment by SEETHAMRAJU** [comment]
_import aimet
Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
ModuleNotFoundError: No module named 'aimet'_
This is the error that I am getting after running **buildntest.sh -i**

**Comment by quic-bharathr** [comment]
@SEETHAMRAJU Do you still have this issue? It looks like you're trying to import a module that does not exist. Could you please follow the code examples from the API documentation based on your use-case?
https://quic.github.io/aimet-pages/AimetDocs/api_docs/index.html

You mentioned you tried importing the package after you got into the interactive terminal. Did you follow the steps to build the code and setup the environment variables starting at the sections below?
https://github.com/quic/aimet/blob/develop/USAGE.md#build-code-and-install
