### ISSUE TITLE
Multiple inputs

### ISSUE THREAD

**Issue by KTAN119** [quic/aimet#403]
If my model is designed to accept two inputs, what should I put in the input_shape argument in the ModelCompressor.compress_model()?

**Comment by quic-ssiddego** [comment]
Hi @KTAN119 Assuming this is the PyTorch model : Yes, we would need to pass a **list of tuples** of shapes corresponding to each of the input nodes. Please let us know if you have any issue using it.

**Comment by quic-akhobare** [comment]
No update in a while.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
