### ISSUE TITLE
Unable to install AIMET library html doc

### ISSUE THREAD

**Issue by akssieg** [quic/aimet#404]
I followed the installation setup instructions available at https://github.com/quic/aimet/blob/develop/packaging/docker_install.md.

I tried manually building the docker image then starting it with the command:

`docker run --gpus all --rm -it -v ${WORKSPACE}:${WORKSPACE} --entrypoint /bin/bash -w ${WORKSPACE} --hostname aimet-dev ${docker_image_name}`

The installation was successful but when I tried building the docs using following the commands:
```
cd $WORKSPACE/build
make doc
```
```
writing output... [100%] user_guide/winnowing                                                                                                 
generating indices... genindex
writing additional pages... search
copying images... [100%] user_guide/../images/winnow_2.png                                                                                    
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 4 warnings.

The HTML pages are in ..
Built target doc
```

The `$WORKSPACE/build/staging/universal/Docs` was empty and there was no generation of user_guide/index.html page. 

Can somebody please point me in the right direction ?

@quic-akhobare @quic-hitameht @quic-mangal @quic-klhsieh @quic-bharathr

**Comment by quic-ssiddego** [comment]
Hi @akssieg Thank you for reporting this error. There is perhaps a correction required to the documentation. Please find the documentation under $WORKSPACE/**build/Docs**.  Could you please try this and let us know.

**Comment by akssieg** [comment]
Thanks @quic-ssiddego, docs are accessible under $WORKSPACE/build/Docs.

**Comment by quic-akhobare** [comment]
Excellent. @akssieg - could you please close the issue?
