### ISSUE TITLE
Visualization API not working inside Docker

### ISSUE THREAD

**Issue by Rohan-Chaudhury** [quic/aimet#406]
Hi,

I was trying to run the following code from inside aimet docker:

```
def visualize_weight_ranges_model(model):
    """
    Code example for model visualization
    """
    visualization_url, process = start_bokeh_server_session(25000)
    model = model.to(torch.device('cpu'))

    batch_norm_fold.fold_all_batch_norms(model, (1,1, 28, 28))

    # Usually it is observed that if we do BatchNorm fold the layer's weight range increases.
    # This helps in visualizing layer's weight
    visualize_model.visualize_weight_ranges(model, visualization_url)
```

But bokeh server was not showing any visualizations and it was giving the following message:
```
2021-01-22 21:28:53,652 Refusing websocket connection from Origin 'http://localhost:25000';                       
use --allow-websocket-origin=localhost:25000 or set BOKEH_ALLOW_WS_ORIGIN=localhost:25000 to permit this; currently we allow origins {'aimet-dev:25000'}
```

**Comment by quic-ssiddego** [comment]
Hi @Rohan-Chaudhury  Thank you for reporting the error and also submitting a potential fix for it. To merge the fix  to open source : Could you please : (1) squash the commits on the PR to a **single** **commit** (2) update the commit message to indicate what has been fixed (example commit message: "bokeh fix to enable websocket connections originating from additional hosts in visualization api". Please do let us know if you have any questions.

**Comment by Rohan-Chaudhury** [comment]
Hi @quic-ssiddego,
I have squashed the commits and added an appropriate commit message as per your suggestions. Please have a look and let me know if anything else should be added.

Thanks,
Rohan

**Comment by quic-ssiddego** [comment]
@Rohan-Chaudhury  Thank you for the quick updates on this one. PR looks good. Approved and merged.
