### ISSUE TITLE
Can we compress/quantize any arbitrary model?

### ISSUE THREAD

**Issue by listener17** [quic/aimet#408]
Before spending time in installing and trying out AIMET on my PyTorch model, I was curious to know the following:
1. Does AIMET support all the PyTorch layers and operators? If not, is there any such documentation? My model has 1d convolution and 1d transposed convolution layers, PRelu's Leaky Relu's , LSTMs, etc.
2. What happens if AIMET doesn't support something? Does it throw off an error, or does it simply not compress unsupported layers?

**Comment by quic-ssiddego** [comment]
Hi @listener17 Thank you for your query. (1) AIMET compression supports CONV2D and Linear types. Quantization in-theory can work on any layer type. You could give it a try on your model and let us know in case of any issues. (2) Compression simply ignores the unsupported layers during compression. Quantization would thrown some error messages if it hits an unhandled type. Please let us know if you have further questions.

**Comment by listener17** [comment]
Hi @quic-ssiddego: 

Thanks. 
So, it wouldn't be able to compress a network which predominantly consists of 1d conv and 1d transposed conv (like U-Net). 
Where can I find information on the supported layers?

**Comment by quic-ssiddego** [comment]
@listener17 
That's right. It wouldn't support the 1D conv and 1D transpose conv.  Please note that the currently supported ones are Conv2D and Linear types. We will add this information on supported types to our documentation soon. Have created a issue for same https://github.com/quic/aimet/issues/469

Please let us know if you have further queries.

**Comment by listener17** [comment]
Thanks @quic-ssiddego So, I'm closing the issue. I will follow AIMET development and I'll start trying when the toolbox matures a bit more.
