### ISSUE TITLE
Could not access Nvidia CDN from some country.

### ISSUE THREAD

**Issue by zhanghaocol** [quic/aimet#424]
Hi, guys:
For those that in some country could not access official nvidia CDN server, the docker build process would be broken, would you mind to add some deb source to do this. 

https://github.com/quic/aimet/pull/423

**Comment by quic-akhobare** [comment]
AIMET can be installed on pure CPU machines as well. Using the right CPU packages.

Closing this ticket. If there is a follow-up question please re-open or create a new issue.
