### ISSUE TITLE
Issue with python install

### ISSUE THREAD

**Issue by ghost** [quic/aimet#433]
Hi,
I find aimet install a little bit complex compared to other frameworks (tensorflow, pytorch)? Why can't we install it with a simple "pip install aimet"?
I have an issue with import of "libpymo". Where can we find this lib ?

Do you plan to support aimet install within conda environment?

Regards,
Oc

**Comment by jdmedinatobon** [comment]
I'm having the same problem. +1

**Comment by jdmedinatobon** [comment]
Hi! I think I solved. 
Make sure you go through the Environment setup detailed here: https://github.com/quic/aimet/blob/develop/packaging/install.md
Environment variables are discarded when you exit a terminal, so you have to do this every time you start one. You can try adding the commands to the .bashrc file.
Hope it helps.

**Comment by quic-ssiddego** [comment]
@jdmedinatobon  Thanks for the update. @ocaff1 Please let us know if this is still an issue. We are looking into simplifying the libpymo import.

**Comment by ghost** [comment]
Hi, 
I am still facing issues with the install.
I work within anaconda env. I have installed cudatoolkit 10.2 and still I cannot make it...

I used pytorch intensively with cuda and I do not have any issue. 
I think it would be nice to have a ligther install mechanism for aimet.

Regards,
Olivier

My setup (ubuntu 18.04):

_AIMETPATH=~/anaconda3/envs/aimet/lib/python3.6/site-packages/aimet_common
source $AIMETPATH/bin/envsetup.sh
export PATH=$AIMETPATH/x86_64-linux-gnu:$PATH
export LD_LIBRARY_PATH=$AIMETPATH/x86_64-linux-gnu:$AIMETPATH:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH_

My python test:
"
import aimet_common
import aimet_torch
from aimet_torch.quantsim import QuantizationSimModel
"

Result =>  
import libpymo
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

**Comment by jdmedinatobon** [comment]
Hmm it might be the version of cuda. I installed cuda version 10.0 instead of 10.2.
Maybe you can try reinstalling your cuda version. I checked inside my cuda folder and I have a libcublas.so.10.0 file. I'm guessing this file doesn't exist if you install cuda version 10.2, maybe it's called libcublas.so.10.2 or so.

**Comment by quic-bharathr** [comment]
Hi @ocaff1 and @jdmedinatobon: We have a new release with simpler instructions. Please feel free to try it out and let us know if any issues:
- Release: https://github.com/quic/aimet/releases/tag/1.16.1
- Instructions: https://github.com/quic/aimet/blob/1.16.1/packaging/install.md

**Comment by tucachmo2202** [comment]
Hi @quic-bharathr, I install torch_cpu 1.16.2 and met this error when run eval_ssd.py file 
` import libpymo
ImportError: liblapacke.so.3: cannot open shared object file: No such file or directory
`

**Comment by hanyueqian2** [comment]
@tucachmo2202 may I ask how to solve this problem? I have the same problem.I install tf_cpu 1.16.2.

**Comment by hanyueqian2** [comment]
import libpymo ImportError: liblapacke.so.3: cannot open shared object file: No such file or directory
I think i solved this problem.
sudo apt-get install liblapacke-dev  
In  the /usr/lib/x86_64-linux-gnu directory，there will be this file. Then move this file to the same level directory of  libpymo.so .
My directory is   ./.conda/envs/aimetTf16_2/lib/python3.6/site-packages/aimet_common/x86_64-linux-gnu .
希望能帮到你

**Comment by tucachmo2202** [comment]
> import libpymo ImportError: liblapacke.so.3: cannot open shared object file: No such file or directory
> I think i solved this problem.
> sudo apt-get install liblapacke-dev
> In the /usr/lib/x86_64-linux-gnu directory，there will be this file. Then move this file to the same level directory of libpymo.so .
> My directory is ./.conda/envs/aimetTf16_2/lib/python3.6/site-packages/aimet_common/x86_64-linux-gnu .
> 希望能帮到你

Thank you,
I solved the problem!

**Comment by quic-akhobare** [comment]
Closing this ticket. If there is a follow-up question please re-open or create a new issue.
