### ISSUE TITLE
Issue with creating docker image

### ISSUE THREAD

**Issue by marjanemd** [quic/aimet#44]
Following the instructions of aimet/USAGE.md, while building the docker, I need to specify the docker's name, and I have defined it as :
docker_image_name='img:f14'

But getting the error that the argument is invalid. I have searched about the issue, and I believe the format of the definition is correct!
Appreciate any help!

**Comment by quic-akhobare** [comment]
Thanks for the report @marjanemd. Can you please post the error message?

**Comment by marjanemd** [comment]
Sure. I have named my docker as: 

`docker_image_name="docker_img:f123"`
 But once I run 

`docker build -t ${docker_image_name} -f $WORKSPACE/aimet/Jenkins/Dockerfile .`
I get the following error:

_invalid argument ":f123" for "-t, --tag" flag: invalid reference format
See 'docker build --help'._

In the help it has also mentioned that the docker image name and tag should be in format of : 'name:tag' 
which it already is!

I really appreciate your help.

**Comment by quic-bharathr** [comment]
@marjanemd Do you still have this issue? I was able to build a docker using the exact same name and tag you mentioned above. What version of docker are you using? Is your environment identical or close to the requirements here? https://github.com/quic/aimet/blob/develop/USAGE.md#requirements
