### ISSUE TITLE
libaimet_tf_ops.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by suakim** [quic/aimet#458]
Hello, I tried to use aimet_tensorflow and import BiasCorrectionParams, QuantParams, BiasCorrection from aimet_tensorflow.bias_correction, but there is an error on libaimet_tf_ops.so. 
Is it a bug or did I something wrong?

I share a colab link [here](https://colab.research.google.com/drive/1k4VVF2usJp3XBKk-VTnO86Ra6749tFi6?usp=sharing). 

Thank you in advance.

**Comment by justacasul** [comment]
@suakim Hello friend, I'm facing this same issue. Since you closed the issue, did you manage to find a solution?

**Comment by Jia-HongHenryLee** [comment]
Hi @suakim,  I solve this problem.  https://github.com/quic/aimet/issues/1370
