### ISSUE TITLE
Model heavier after quantisation

### ISSUE THREAD

**Issue by bluesky314** [quic/aimet#459]
Tried to quantise a model however:

1) The returned model was in fp32
2) Was heavier than original model

Can someone explain what may have gone wrong?

Thanks

**Comment by quic-ssiddego** [comment]
@bluesky314 Thank you for your query.
In any case : 1] Yes, a FP32 is returned. AIMET does not quantize models. It is a optimization tool to make 
models optimal for quantized targets. AIMET also provides quantization simulation capability.
Please find more details on Quantization on AIMET here : 
https://quic.github.io/aimet-pages/AimetDocs/user_guide/model_quantization.html#ug-model-quantization.
Please let us know if you have further queries.

**Comment by sarakarami023** [comment]
@quic-ssiddego, given a model is XMB , are you saying if we run the quantized model on  target, it only needs XMB/4 memory footprint ( FP32 to INT8)?. Can you please elaborate how AIMET helps with memory footprint?

**Comment by quic-akhobare** [comment]
Hi @sarakarami023  - yes thats correct.

**Comment by quic-akhobare** [comment]
Hope that answers your question. Closing this for now. Please re-open if you have a follow-up question.
