### ISSUE TITLE
Should model pruning be done before quantization or after?

### ISSUE THREAD

**Issue by LLNLanLeN** [quic/aimet#509]
I have more of a question about AIMET. When should we apply pruning to the model? Should we do it before quantization ? Or should we prune the model after quantization? 

Thank you

**Comment by quic-akhobare** [comment]
Hi @LLNLanLeN. Yes we recommend model compression followed by model quantization.

**Comment by LLNLanLeN** [comment]
@quic-akhobare  Thank you for the quick response, it seem that my understanding has been quantize then compress. I'll look into model compression before quantizing then. Thank you.
