### ISSUE TITLE
Support for DepthwiseConv2d

### ISSUE THREAD

**Issue by anirudth** [quic/aimet#52]
Will there be support for DepthwiseConv2d in the future for Spatial/Weight SVD pruning and Channel Pruning?

**Comment by quic-ssiddego** [comment]
@anirudth Thank you for the query. With regard to Spatial SVD : The tensor decomposition does not lend itself to allow SVD for depthwise layers, so we cannot do spatial SVD. And, w.r.t Channel pruning - Depthwise layers are not compute heavy - hence, currently omitted. But, we could perhaps add support for it in the future.
