### ISSUE TITLE
evaluate_model and train_model functions not available in the video tutorials

### ISSUE THREAD

**Issue by flaviomb** [quic/aimet#53]
Hello, I'm learning about how to use the Qualcomm aimet toolkit. 

I'm watching the video tutorials to reproduce the examples (specifcally this one about quantization: [https://www.youtube.com/watch?v=0-i64DelNkI&t=1107s]() ). 
In these videos, the author uses the `evaluate_model` and `train_model` functions but I did not found it for download.

Here is the code to import the functions used in the videos:

`from pipelines import evaluate_model, train_model`

Could you provide these functions?

Thanks in advance.

**Comment by quic-ssiddego** [comment]
@flaviomb Thank you for trying out the tutorial. The tutorial demonstrates these as ‘user’ provided functions to be passed to the API provided by the tool.  If you already have a training pipeline, you could pass your existing evaluate and train functions.

**Comment by pianogGG** [comment]
@quic-ssiddego How can I run successfully the script in the video and where I can find the script?

**Comment by kanybekasanbekov** [comment]
@pianogGG Here are some codes used in video tutorial(https://github.com/quic/aimet/tree/develop/Docs/torch_code_examples). Some functions like `evaluate_model()` should be implemented by yourself, however, you can at least get function format which will be helpful

**Comment by TengFeiHan0** [comment]
would you mind to open the pipeline.py shown in this video? we can take it as a reference to develop our own code. @quic-ssiddego  @quic-akhobare

**Comment by quic-ssiddego** [comment]
@pianogGG  @kanybekasanbekov  @TengFeiHan0  Sorry about the delayed response on this thread. We are adding more detailed examples such as https://github.com/quic/aimet/tree/312905d4efa856f2684935566a9e3dac74f7677d/Examples/torch/compression. There will be similar one added for quantization as well.

**Comment by quic-akhobare** [comment]
We have added several working example notebooks now. Closing this ticket.
