### ISSUE TITLE
CUDA 11 / RTX 30XX support

### ISSUE THREAD

**Issue by struemya** [quic/aimet#539]
Dear Collaborators,

Is there currently an installation procedure that supports CUDA 11 and the newer Ampere GPUs?

I have tried to modify the docker build to use the current versions of CUDA etc. without success. It is still asking for the libpymo.so.10.0 file.

I have also tried downgrading to CUDA 10 which unfortunately does not seem to work with my setup (RTX 3070, Ubuntu 18.04), as it freezes when .cuda() is called.

I would be grateful for any support.

**Comment by quic-bharathr** [comment]
@struemya Do you want to use AIMET with pytorch models or tensorflow?

**Comment by struemya** [comment]
> @struemya Do you want to use AIMET with pytorch models or tensorflow?

Thanks for your reply. I would like to use it with pytorch models.

**Comment by quic-bharathr** [comment]
Hi @struemya We are working on adding CUDA 11 support with Torch 1.7. We'll update this repo when it is ready (ETA is within 2 weeks).

**Comment by quic-bharathr** [comment]
Hi @struemya: We now have a new release and instructions with support for PyTorch 1.7 and Cuda 11.x. Could you please try it out and let us know if any issues?
- Release: https://github.com/quic/aimet/releases/tag/1.16.1
- Instructions: https://github.com/quic/aimet/blob/1.16.1/packaging/install.md

**Comment by struemya** [comment]
Hi @quic-bharathr,
I can confirm that the new release works on with Cuda 11 on my RTX3070. 
Thanks a lot!
