### ISSUE TITLE
Cannot install AIMET package on raspberry pi3.

### ISSUE THREAD

**Issue by neeraj-partha** [quic/aimet#556]
Could not find a version that satisfies the requirement torch==1.4+cu100 (from AimetCommon==1.14.0) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
No matching distribution found for torch==1.4+cu100 (from AimetCommon==1.14.0)

**Comment by quic-ssiddego** [comment]
@quic-bharathr could you please take a look at this.

**Comment by quic-bharathr** [comment]
Hi @neeraj-partha ,
What installation command did you run when you saw the above failure? Was it (similar to) this?
python3 -m pip install https://github.com/quic/aimet/releases/download/1.14.0/AimetCommon-1.14.0-py3-none-any.whl -f https://download.pytorch.org/whl/torch_stable.html

We've not tested this on Raspberry PI. Our supported platform requirements are documented here:
https://github.com/quic/aimet/blob/develop/packaging/docker_install.md#requirements

**Comment by quic-hitameht** [comment]
Mark this as resolved. If you have further questions please re-open or create a new issue.
