### ISSUE TITLE
installation guide for pytorch 1.8+cuda 11.1

### ISSUE THREAD

**Issue by cli99** [quic/aimet#573]
Can you update the installation guide for 1.16.0 release? Does it support pytorch 1.8 and cuda 11.1?

Thanks.

**Comment by quic-ssiddego** [comment]
@quic-bharathr Could you please take a look at this

**Comment by quic-bharathr** [comment]
Hi @cli99 Apologies for the inconvenience. We will update the installation guide for the 1.16.0 release within the next few days. The release supports PyTorch 1.7.1 and cuda 11.1.

**Comment by quic-bharathr** [comment]
Hi @cli99: We now have a new release and instructions with support for PyTorch 1.7 and Cuda 11.x. Could you please try it out and let us know if any issues?
- Release: https://github.com/quic/aimet/releases/tag/1.16.1
- Instructions: https://github.com/quic/aimet/blob/1.16.1/packaging/install.md

**Comment by quic-hitameht** [comment]
Mark this as resolved. If you have further questions, please re-open or create a new issue.
