### ISSUE TITLE
docker tests not working

### ISSUE THREAD

**Issue by mikeseven** [quic/aimet#583]
following install procedure to create docker image, then calling `./buildntest.sh`
using options to run tests, nothing passes even though docker is correctly called with flags for GPU etc.

Other dockers on the machine work correctly so I doubt it's an issue with docker runtime but in case, here is the host system configuration:
- OS ubuntu 20.04
- cuda 11.2

**Comment by quic-ssiddego** [comment]
Tagging @quic-bharathr  for inputs on this one.

**Comment by quic-bharathr** [comment]
Hi @mikeseven Could you please share the failure logs? The build instructions may be out of date and we'll update them shortly.

**Comment by quic-hitameht** [comment]
HI @mikeseven Marking this as resolved. If you have further questions please re-open or create a new issue.
