### ISSUE TITLE
Does AIMET support mix-precision quantization?

### ISSUE THREAD

**Issue by tonylt** [quic/aimet#626]
Hi, thanks for you guys work on model compression and quantization toolkit, we are using it to quantize our models.
Does it support mix-precision quantization? Is there any docs or samething I can use?

Thans!

**Comment by quic-ssiddego** [comment]
Hi @TonyMou Thank you for your query. Could you please elaborate on your use case that needs mixed precision? Currently, we do support user configurable param and output quantizer bitwidths - that can be manually configured using QuantSimModel.  Could you please share if this for Tensorflow or PyTorch model? We could point you to appropriate code example accordingly.

**Comment by quic-hitameht** [comment]
Hi @TonyMou marking this as resolved. If you have further questions please re-open or create a new issue. Thank you!
