### ISSUE TITLE
Compatibitliy of CLE and Bias Correction with MLPs

### ISSUE THREAD

**Issue by struemya** [quic/aimet#644]
Dear Collaborators,

I have tried to use Cross-Layer-Equalization and Bias Correction with an MLP architecture.
In case of the CLE the Linear layers seem to be ignored by the equalize_model function.
For Bias Correction, I am experiencing issues with the input rank requirement that seems to be specifically designed to work with images. In particular, my input has one dimension less than what is required (->4). Adding a dummy dimension causes further dimension issues down the line.

My main question is whether this is the expected behaviour, or if the code is supposed to work with MLPs as well. In principle, I don't see a reason why CLE and BC should not be applicable to MLPs.
Best,
Yannick

**Comment by quic-akhobare** [comment]
Hi @struemya 

You bring up an interesting point. We have not really tried CLE with layers other than convolutional layers and their variants. However, it seems to me that CLE should work technically with linear layers. Do you want to take a stab at making changes for this? One of the authors can guide you along..

- If yes, I would suggest that you start bottom up. Meaning start by making this method work for linear layers. 
aimet_torch.cross_layer_equalization.scale_cls_set()
- You may need to extend the shape dimensions by 2 via a reshape

For the Bias correction, yeah the short answer is that we have not tried that with linear layers. But it should be easy to extend to cover linear layers as well. Maybe we can start with CLE first before we tackle this.

Let me know your thoughts?

**Comment by struemya** [comment]
Hi @quic-akhobare,
Thanks for your answer. We have realised in the meantime that CLE can only work with ReLU activations and we are using different activations. Moreover, BC is not recommended in conjunction with Adaround as far as I understand and adaround works well so far. If we consider switching out the activations, we might try to implement CLE for linear layers.

**Comment by quic-akhobare** [comment]
Thanks for the update @struemya. Should we close this ticket, if there is nothing else outstanding?

**Comment by struemya** [comment]
yes that is fine :)
