### ISSUE TITLE
Add support to identify [Conv - Relu6] as supergroup

### ISSUE THREAD

**Issue by quic-ssiddego** [quic/aimet#672]
- Add support for conv -> relu6 supergroup in quantsim config json file

From a complexity perspective, this ticket is at an easy level.

**Comment by mohanksriram** [comment]
Hi @quic-ssiddego, I would like to start with this issue.

**Comment by quic-ssiddego** [comment]
Thank you for the quick response @mohanksriram. Would like to introduce you to team members who can help you get started with this @quic-akhobare  @quic-klhsieh. @quic-klhsieh,  could you please add the necessary details to this issue and enable @mohanksriram. Thank you.

**Comment by quic-klhsieh** [comment]
Thank you for your interest in taking up this issue @mohanksriram. Here are some additional pointers to help you get started:

Supergroups are used during quantization simulation to identify groups of operations which will not have quantization done in between. Different runtimes may use different rules, so we provide users the flexibility to configure supergroups and other settings using a json configuration file. default_config.json under aimet_common/quantsim_config holds some default settings which we typically find common between runtimes. Conv->Relu6 rule can be added in here.

The configuration files are used for both pytorch and tensorflow quantization simulation. To understand how we use it for each framework, you can start looking at quantsim_config.py under aimet_torch/quantsim_config and aimet_tensorflow/quantsim_config respectively.

To test for correctness, please also create unit tests within test_quantsim_config.py under torch/test/python and tensorflow/test/python for both frameworks.

**Comment by quic-ssiddego** [comment]
Hi @mohanksriram Just wanted to check back on this. Were you able to checkout code and make updates? Please let us know if you have further questions. Thank you.
