### ISSUE TITLE
Update TF Bias Correction to use new Quantsim implementation

### ISSUE THREAD

**Issue by quic-ssiddego** [quic/aimet#674]
- Deprecate the usage of old quantsim implementation
- Update bias correction implementation to use new quantsim api

If you are interested in working on this issue - please indicate via a comment on this issue. It should be possible for us to pair you up with an existing contributor to help you get started.

From a complexity perspective, this ticket is at an easy level.

**Comment by balajikulkarni** [comment]
@quic-ssiddego I would like to contribute to AIMET and looking for a good first issue, but seems most of the recent ones are being picked up. Could you please point to any easy level ticket?

**Comment by quic-akhobare** [comment]
old ticket. This has been resolved already.
