### ISSUE TITLE
hot to export int8 onnx model?

### ISSUE THREAD

**Issue by xunyiljg** [quic/aimet#69]
I need to import onnx into the unity engine, but aimet only exports the 32 float version. 
In theory, it can export int8 model by adding the information from encoding json directly to the model inference section, right? 

Aimet is a great optimization tool, but I don't use the Qualcomm SDK. Can you support the above features.

**Comment by quic-akhobare** [comment]
Thanks for the query @xunyiljg. This has been on our mind. But I am not sure yet how to do this specifically for onnx.

Have you played with exporting a quantized pytorch model to ONNX yet? Any pointers will be appreciated.

**Comment by quic-akhobare** [comment]
We have export logic now that exports the ONNX model and corresponding encodings via a separate file. Also there is a mode to inject the quantization encodings into the model itself via QuantizeLinear and DequantizeLinear nodes.

Closing the ticket.
