### ISSUE TITLE
Would you please provide the compressed ResNet50 model of 75.75% accuracy? Thanks! 

### ISSUE THREAD

**Issue by lyleffective** [quic/aimet#716]
Hello! 

It seems that the compressed ResNet50 is not provided, would you please consider uploading it, just like the quantized models? 

Thanks a lot!

**Comment by quic-ssiddego** [comment]
Hi @lyleffective Thank you for the query. We do not host the compressed models at the moment on model zoo- we could consider that in future. But, you could check the examples here : https://github.com/quic/aimet/tree/develop/Examples/torch/compression to use the apis(s) and apply compression on a given model. Please let us know if you have further queries

**Comment by lyleffective** [comment]
Thanks for your answer! I hope that the compressed models can be added to the model zoo in the future!

**Comment by wangshankun** [comment]
> 

Could you provide the resnet50 compressed config(or args) for official compression ratio of 0.5 ?

For Example:
    num_reconstruction_samples、num_comp_ratio_candidates、Number of epochs for finetuning····


I want repeat it;
