### ISSUE TITLE
After Quantization Simulation,whether the model will become smaller

### ISSUE THREAD

**Issue by hanyueqian2** [quic/aimet#733]
```
model = models.MobileNetV2(num_classes=4).cpu()
sim = QuantizationSimModel(model, default_output_bw=8, default_param_bw=8,
                           dummy_input=torch.rand(batch_size, 3, 512, 512))
sim.compute_encodings(forward_pass_callback=aimet_evaluate_model, forward_pass_callback_args=None)
train_model(model=sim.model，...）
sim.export(path='saved_models', filename_prefix='tmp', dummy_input=torch.rand(batch_size, 3, 512, 512))
```

Final result (onnx) did not get smaller(8.6M -> 8.8M).Could you give me some advice and help me to solve these problems?

**Comment by hanyueqian2** [comment]
The quantization result of the example, the onnx file is not quantized and pseudo-quantized. Is this correct?
Can the model after QAT be exported onnx? Are training and quantization independent of each other?

**Comment by quic-ssiddego** [comment]
@hanyueqian2  Thank you for your query. One of the use-cases of quantization simulation supported by AIMET is to study the impact of  fixed point arithmetic performed by HW platform on your model performance. This is done by simulating the quantization induced noise by applying quantize/dequantize on op params / activations, based on config rules. 
AIMET supports export() functionality to export the onnx and corresponding encodings file that can be taken and injected to runtime - please refer the example usage here : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L689
Further, a user can also create a quantization simulation model and perform training (fine-tune) the performance. Please refer to example : https://github.com/quic/aimet/blob/develop/Examples/torch/quantization/quantization_aware_training.py for training with quant-sim model. Here's some documentation reference for quantization support on AIMET : https://quic.github.io/aimet-pages/releases/1.16.2/user_guide/model_quantization.html#ug-model-quantization. Please let us know if you have further queries.

**Comment by hanyueqian2** [comment]
Thank you very much, I get it.
