### ISSUE TITLE
mixed precision for QAT

### ISSUE THREAD

**Issue by lovodkin93** [quic/aimet#758]
Hello,
does your model support mixed precision for QAT?
And if so, could you please upload such an example for tensorflow?
Thanks!

**Comment by quic-ssiddego** [comment]
Hi @lovodkin93 Sorry about the delayed response. AIMET quantization simulation offers configuration knobs at a tensor level that enable application of mixed precision to a given model. Please refer to this code example (unit test), for more details on how you could control parameter and activation quantizers configurations: https://github.com/quic/aimet/blob/develop/TrainingExtensions/tensorflow/test/python/test_quantsim.py#L610
Please let me know if you have further questions.

**Comment by quic-ssiddego** [comment]
@lovodkin93  We will be  closing this issue for now. Please re-open if further assistance from AIMET team is needed. Thank you.
