### ISSUE TITLE
Support multiple inputs in BIas Correction Quantization?

### ISSUE THREAD

**Issue by WeiyiLi** [quic/aimet#779]
Hello,

I have a model with two inputs with different size. I constructed the dataloader and applied `bias_correction.correct_bias`, but I got error 
 ```
 File "test_aimet.py", line 107, in <module>
    data_loader=data_loader, num_bias_correct_samples=num_bias_correct_samples)
  File "/home/kathy/anaconda3/envs/perf/lib/python3.7/site-packages/aimet_torch/bias_correction.py", line 265, in correct_bias
    ordered_conv_linear_nodes = get_ordered_lists_of_conv_fc(model, input_shape)
  File "/home/kathy/anaconda3/envs/perf/lib/python3.7/site-packages/aimet_torch/utils.py", line 536, in get_ordered_lists_of_conv_fc
    module_list = get_ordered_list_of_modules(model, dummy_input)
  File "/home/kathy/anaconda3/envs/perf/lib/python3.7/site-packages/aimet_torch/utils.py", line 440, in get_ordered_list_of_modules
    run_hook_for_layers_with_given_input(model, dummy_input, hook=_hook_to_collect_name_of_module)
  File "/home/kathy/anaconda3/envs/perf/lib/python3.7/site-packages/aimet_torch/utils.py", line 278, in run_hook_for_layers_with_given_input
    _ = model(*input_tensor)
  File "/home/kathy/anaconda3/envs/perf/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'uv'
```

I digged into the source code and found in file `aimet_torch/utils.py`, in function `get_input_shape_batch_size`, it only returns one shape. How can I make it support multiple inputs in bias correction? Thank you.

**Comment by quic-ssiddego** [comment]
Hi @WeiyiLi  Thank you for your query. Sorry about the delayed response. In the current implementation of bias correction we do not have support for multiple input case. However, you could consider extending the current design to do so. Here's a sample code you could use to extend this https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/src/python/aimet_torch/adaround/activation_sampler.py#L59 
utilize ModuleData type for this purpose :
https://github.com/quic/aimet/blob/755c245692d86d18198cd2d1cd962b837f2c9ab1/TrainingExtensions/torch/src/python/aimet_torch/utils.py#L79
Getting input shape : https://github.com/quic/aimet/blob/755c245692d86d18198cd2d1cd962b837f2c9ab1/TrainingExtensions/torch/src/python/aimet_torch/utils.py#L397
This approach needs to be used to replace current implementation in bias correction : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/src/python/aimet_torch/bias_correction.py#L334

Please take a look at above and let us know in case of further questions.
Also, adding @quic-hitameht to thread for support in case @WeiyiLi chooses to implement this option.

**Comment by quic-hitameht** [comment]
Hi @WeiyiLi Closing this as resolved. If there is another question please re-open or create a new issue. Thank you.
