### ISSUE TITLE
Missing files installing AIMET via Google Colab

### ISSUE THREAD

**Issue by TTTiko** [quic/aimet#791]
when I use google colab to install AIMET, I made an error in the steps shown in the picture. 

![image](https://user-images.githubusercontent.com/65775863/138993813-c23db386-6672-4c3d-a99f-d9d46883cfcc.png)

The error message is that the requirement.txt file cannot be found.

![image](https://user-images.githubusercontent.com/65775863/138993754-2ac0d499-cff7-495a-95ba-6e327fc1db64.png)

how can i solve it? thank you very much # @quic-bharathr @quic-akhobare

**Comment by quic-ssiddego** [comment]
@quic-bharathr could you please take a look at this issue?

**Comment by hy-chen** [comment]
Same issue here

**Comment by songh11** [comment]
> 

Hi
    I changed my code like this.

!apt-get install liblapacke
!apt-get install wget
!apt-get install cuda-command-line-tools-11-0
!pip install ipython==7.16.1
!pip install numpy==1.16.4
!pip install scipy==1.1.0
!pip install protobuf==3.7.1
!pip install scikit-learn==0.19.1
!pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torchaudio==0.7.2
!pip install torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html
!pip install future==0.17.1
!pip install bokeh==1.2.0
!pip install pandas==1.1.1
!pip install holoviews==1.12.7
!pip install hvplot==0.4.0
!pip install jsonschema==3.1.1
!pip install osqp==0.6.1
!pip install onnx==1.7.0

**Comment by quic-sendilk** [comment]
@TTTiko, please reopen the ticket if its still an issue. Thanks
