### ISSUE TITLE
Docker in docker hub

### ISSUE THREAD

**Issue by tucachmo2202** [quic/aimet#804]
Thank your great work!
I want to install aimet tool in a remote server without root permission. Are there any Docker version for aimet in docker hub?

**Comment by quic-ssiddego** [comment]
Hi @tucachmo2202 Thank you for your query. Adding @quic-bharathr for inputs on this.

**Comment by quic-bharathr** [comment]
Hi @tucachmo2202 sorry at this time, we do not have a docker image available. You can either install our pre-built releases (https://github.com/quic/aimet/releases) using these instructions: https://github.com/quic/aimet/blob/develop/packaging/install.md

OR you can build the docker yourself using one of the dockerfiles provided (https://github.com/quic/aimet/tree/develop/Jenkins) and then build aimet within the docker using these instructions: https://github.com/quic/aimet/blob/develop/packaging/docker_install.md

**Comment by luyi404** [comment]
Hi @quic-bharathr , thank you for your effort. But when I was trying to install the AIMET in my pytorch-gpu docker, there are so many faults keep appearing😭 and it is so hard to fix some of them.
I believe if your team could commit an official docker image in docker hub could really help other people better try this tool quickly. 😊
