### ISSUE TITLE
problem about Quantization Simulation

### ISSUE THREAD

**Issue by ayenuaa** [quic/aimet#806]
hi,
I trained Yolov3 by Pytorch. I found that the mAP of aimet simulation is lower than the mAP of DSP.  The eval set contains 1000 images.  Here are the code of aimet simulation and config file.  I found that  the input and output of model can only be set to 8bit during aimet simulation, which due to the gap between the aimet simulation and inference on DSP ？ 
And the quantization configuration in Aimet Zoo(https://github.com/quic/aimet-model-zoo/blob/develop/zoo_torch/Docs/MobileNetV2-SSD-lite.md) shows that the model inputs are not quantized. But only is_input_quantized=True or is_output_quantized=True can be supported. This is obviously contradictory.  I need your help , thanks. @mohanksriram @Rohan-Chaudhury @aimetci @quic-bharathr @quic-mangal 
```
device = "cuda"
model = Yolov3()
model.to(device)

weights = torch.load('yolov3_float.pth')
model.load_state_dict(weights, strict=True)
eval_func = model_eval(eval_loader)

model.eval() 

input_shape = (1, 1, 224, 224)
model.to(torch.device('cuda'))
dummy_input = torch.ones(input_shape).cuda()

quantsim = QuantizationSimModel(model=model, quant_scheme='tf', dummy_input=dummy_input, rounding_mode='nearest', default_output_bw=8, default_param_bw=8, in_place=False)

quantsim.compute_encodings(evaluator, ("cuda"))
accuracy = evaluator(quantsim.model, device='cuda')
```
----
```
{"defaults": {
    "ops": {
            "is_output_quantized": "True"
    },
    "params": {
            "is_quantized": "True"
    },
    "strict_symmetric": "False",
    "unsigned_symmetric": "True"
},
"params": {
    "bias": {
            "is_quantized": "True"
    }
},
"op_type": {},
"supergroups": [
],
"model_input": {
    "is_input_quantized": "True"
},
"model_output": {}}
```
![image](https://user-images.githubusercontent.com/26295078/140023243-270a049e-9f5a-4947-92f3-174ca5a3afc7.png)

**Comment by ayenuaa** [comment]
@quic-ssiddego

**Comment by quic-ssiddego** [comment]
Hi @ayenuaa Thank you for your query. By default each op will be configured with param (weight) quantization and output quantization, unless there are any fusion rules specified. And, you can specify if input to model needs quantization using : 
"model_input": {
    "is_input_quantized": "True"
},
You can set this to "False" to disable model input quantization. 
By default, AIMET uses this default config file:
https://github.com/quic/aimet/blob/develop/TrainingExtensions/common/src/python/aimet_common/quantsim_config/default_config.json. You could override any of these configs by specifying you own config file.
To achieve config suggested on https://github.com/quic/aimet-model-zoo/blob/develop/zoo_torch/Docs/MobileNetV2-SSD-lite.md , you could utilize below "

{
"defaults": {
    "ops": {
            "is_output_quantized": "True"
    },
    "params": {
            "is_quantized": "True"
    },
    "strict_symmetric": "False",
    "unsigned_symmetric": "True",
    "per_channel_quantization": "False"
},
"params": {
    "bias": {
            "is_quantized": "False"
    }
},
"op_type": {},
"supergroups": [
],
"model_input": {
    "is_input_quantized": "False"
},
"model_output": {}
}


And, create quantsim with appropriate quantscheme "tf_enhanced" scheme using :
(example : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L931)
quant_scheme=QuantScheme.post_training_tf_enhanced
 Do let me know if you have further queries. Thank you.

**Comment by ayenuaa** [comment]
> Hi @ayenuaa Thank you for your query. By default each op will be configured with param (weight) quantization and output quantization, unless there are any fusion rules specified. And, you can specify if input to model needs quantization using : "model_input": { "is_input_quantized": "True" }, You can set this to "False" to disable model input quantization. By default, AIMET uses this default config file: https://github.com/quic/aimet/blob/develop/TrainingExtensions/common/src/python/aimet_common/quantsim_config/default_config.json. You could override any of these configs by specifying you own config file. To achieve config suggested on https://github.com/quic/aimet-model-zoo/blob/develop/zoo_torch/Docs/MobileNetV2-SSD-lite.md , you could utilize below "
> 
> { "defaults": { "ops": { "is_output_quantized": "True" }, "params": { "is_quantized": "True" }, "strict_symmetric": "False", "unsigned_symmetric": "True", "per_channel_quantization": "False" }, "params": { "bias": { "is_quantized": "False" } }, "op_type": {}, "supergroups": [ ], "model_input": { "is_input_quantized": "False" }, "model_output": {} }
> 
> And, create quantsim with appropriate quantscheme "tf_enhanced" scheme using : (example : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L931) quant_scheme=QuantScheme.post_training_tf_enhanced Do let me know if you have further queries. Thank you.

https://github.com/quic/aimet/blob/develop/TrainingExtensions/common/src/python/aimet_common/quantsim_config/json_config_importer.py#L140 But the code shows that aimet is not support IS_INPUT_QUANTIZED=False. @quic-ssiddego

**Comment by quic-ssiddego** [comment]
@ayenuaa Ah, that is right. In the current implementation, to achieve this setting, you simply need to remove entry of this specific rule from json file, to disable input quantization 
"model_input": {
**"is_input_quantized": "True"**
}
only when it is be enabled, specify this rule.

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue.
