### ISSUE TITLE
Shape mismatch when apply channel pruning with transpose convolution

### ISSUE THREAD

**Issue by tucachmo2202** [quic/aimet#832]
Hi, Thank your great work!
I met a RuntimeError when applying channel pruning with my [model](https://github.com/microsoft/human-pose-estimation.pytorch/blob/master/lib/models/pose_resnet.py) (the model simple sequential of backbone resnet 18 and three convolution layer): 
Shape mismatch when pruning layer bn2 before layer transpose convolution. 
I applied spartial svd with the model successfully so I think there are something wrong with channel pruning with transpose convolution. 
My aimet version is 1.17.0.
Thank for your help!

**Comment by quic-ssiddego** [comment]
Hi @tucachmo2202 Sorry about the delayed response. Could you please share the full error snippet. 
Tagging @quic-hitameht  @quic-sundarr to follow up on this (check channel pruning support for transpose conv type).

**Comment by tucachmo2202** [comment]
> Hi @tucachmo2202 Sorry about the delayed response. Could you please share the full error snippet. Tagging @quic-hitameht @quic-sundarr to follow up on this (check channel pruning support for transpose conv type).

Hi, I am sorry, I don't save the detail error.

**Comment by quic-ssiddego** [comment]
@tucachmo2202  We will be closing this issue for now. Please re-open it if you need further assistance from AIMET team. Thank you.
