### ISSUE TITLE
wrong gamma and beta for no bn case?

### ISSUE THREAD

**Issue by smallzzy** [quic/aimet#85]
for bias_correction.py#L192, gamma is zero and beta is one?

**Comment by quic-ssiddego** [comment]
Hi @smallzzy Could you please provide more context for this query?

**Comment by smallzzy** [comment]
[This code](https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/src/python/aimet_torch/bias_correction.py#L192) is generating a dummy bn distribution. 
But I think a proper bn distribution should have gamma = 1 and beta = 0?

**Comment by quic-akhobare** [comment]
@smallzzy - :) Thanks for pointing this out. We will check why our tests are passing.

**Comment by quic-ssiddego** [comment]
@smallzzy Thank you for reporting this. Corresponding fix has been merged.
