### ISSUE TITLE
Error when performing channel pruning and spatial svd to efficientNet-b1

### ISSUE THREAD

**Issue by TigerVersusT** [quic/aimet#862]
I' m trying to perform channel pruning to efficientNet-b1 using example code from [here](https://quic.github.io/aimet-pages/releases/1.16.2/api_docs/torch_compress.html#aimet_common.defs.GreedySelectionParameters), but recieved the follwing errors:

**warnings:**
`WARNING:param.Dimension: Use method 'get_param_values' via param namespace
2021-11-25 08:11:20,977 - param.Dimension - WARNING - Use method 'get_param_values' via param namespace
WARNING:param.ParameterizedMetaclass: Use method 'params' via param namespace
2021-11-25 08:11:21,263 - param.ParameterizedMetaclass - WARNING - Use method 'params' via param namespace
WARNING:param.ParameterizedMetaclass: Use method 'params' via param namespace
2021-11-25 08:11:21,263 - param.ParameterizedMetaclass - WARNING - Use method 'params' via param namespace
`
**traceback:**
`Traceback (most recent call last):
  File "ChannelPruningEfficienNetb1.py", line 239, in <module>
    channel_pruning_auto_mode()
  File "ChannelPruningEfficienNetb1.py", line 180, in channel_pruning_auto_mode
    parameters=params)
  File "/home/tiansi/source/aimet/lib/python3.6/site-packages/aimet_torch/compress.py", line 113, in compress_model
    compressed_layer_db, stats = algo.compress_model(cost_metric, trainer)
  File "/home/tiansi/source/aimet/lib/python3.6/site-packages/aimet_common/compression_algo.py", line 87, in compress_model
    layer_comp_ratio_list, stats = self._comp_ratio_select_algo.select_per_layer_comp_ratios()
  File "/home/tiansi/source/aimet/lib/python3.6/site-packages/aimet_common/comp_ratio_select.py", line 232, in select_per_layer_comp_ratios
    current_min_score, current_max_score = self._find_min_max_eval_scores(updated_eval_scores_dict)
  File "/home/tiansi/source/aimet/lib/python3.6/site-packages/aimet_common/comp_ratio_select.py", line 352, in _find_min_max_eval_scores
    first_layer_scores = list(eval_scores_dict.values())[0]
IndexError: list index out of range
`
Additional information: I have follwed guides to make the model both onnx convertable and has no reused model( but still has some ops instead of nn.module ). To debug I tried to print in the evaluation callback function but recieved nothing and the sample code of spatial svd results the same traceback.

Is there anything I omited? Thanks for your help

**Comment by TigerVersusT** [comment]
my fault, I should have first read codes in the example folder

**Comment by quic-ssiddego** [comment]
@TigerVersusT Thank you for reporting this. Tagging @quic-sundarr  @quic-hitameht to take a look at this.

**Comment by quic-hitameht** [comment]
@TigerVersusT Can you please share the script to reproduce this error?

**Comment by TigerVersusT** [comment]
@quic-hitameht @quic-ssiddego  [channelPruning.zip](https://github.com/quic/aimet/files/7708055/channelPruning.zip)
Thanks for your reply, the zip file contains original [efficientNet-pytorch](https://github.com/lukemelas/EfficientNet-PyTorch), the modified tracable version and a python file, you can reproduce the error by runing it with little modification( since you don't need my trained models and datasets ) . 

BTW, I gradually understand the complicity of efficientNets in these days and wrote my pruning codes for efficientNet-b1, hope you can add support for it.

**Comment by quic-ssiddego** [comment]
@TigerVersusT Thank you for the update and the suggestion. Would you like to contribute this to AIMET?

**Comment by BoyuGuan** [comment]
> @quic-hitameht @quic-ssiddego [channelPruning.zip](https://github.com/quic/aimet/files/7708055/channelPruning.zip) Thanks for your reply, the zip file contains original [efficientNet-pytorch](https://github.com/lukemelas/EfficientNet-PyTorch), the modified tracable version and a python file, you can reproduce the error by runing it with little modification( since you don't need my trained models and datasets ) .
> 
> BTW, I gradually understand the complicity of efficientNets in these days and wrote my pruning codes for efficientNet-b1, hope you can add support for it.

Hey! I'm confusing about how to imply pruning for efficientNet,  would you like to share it to me?

**Comment by pablogsanchez** [comment]
I was facing other problems with effientNets:

Problems with layers no supported (added to winnow_utils as SKIP). Not sure if it is the best way to solve the problem...

'ZeroPad2d'

MemoryEfficientSwish'

'adaptive_avg_pool2d'

'sigmoid'

Other error:

expecting  tensor [128,4,1,1] size and current tensor is [128,0,1,1] 

Thanks in advance!!!

**Comment by TigerVersusT** [comment]
I suggest you consider puring efficientnets yourself, search "puring filters for efficient convnets" on github, it's not so difficult as you may think



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 11, 2022 20:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [quic/aimet] Error when performing channel pruning and spatialsvd to efficientNet-b1 (Issue #862)




 
I was facing other problems with effientNets:
 
Problems with layers no supported (added to winnow_utils as SKIP). Not sure if it is the best way to solve the problem...
 
'ZeroPad2d'
 
MemoryEfficientSwish'
 
'adaptive_avg_pool2d'
 
'sigmoid'
 
Other error:
 
expecting  tensor [128,4,1,1] size and current tensor is [128,0,1,1]
 
Thanks in advance!!!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pablogsanchez** [comment]
Thanks for the suggestion, at the moment I was testing [Torch-Pruning ](https://github.com/VainF/Torch-Pruning) But still doing the fine-tuning..... Let's see. 

I will take a look for ur suggestion. :+1: 

Many thanks!!

**Comment by quic-sendilk** [comment]
@pablogsanchez, @TigerVersusT, please reopen the ticket if its still an issue.
