### ISSUE TITLE
AdaRound Example

### ISSUE THREAD

**Issue by PaulZhangIsing** [quic/aimet#896]
I tried to run the AdaRound Example provided in the sample code.
I used the ImageNet validation data downloaded from tf slim
However I only achieved accuracy 0.22 if I turned off from BGR.
the accuracy is higher if I turned on from BGR bool, but it does not make sense as the converted image is in RGB mode

Is there any preprocessing steps I have missed?

I have only doing 3.1 which is calculating the FP accuracy, which already gives me a big trouble already.

 # 3.1. Floating Point accuracy
    accuracy = data_pipeline.evaluate(sess)
    logger.info("Original Model Top-1 accuracy = %.2f", accuracy)

2021-12-17 20:09:22,388 - Eval - INFO - Evaluating graph for 195 iterations with batch_size 256
100% (195 of 195) |##################################################################################################################| Elapsed Time: 0:00:51 Time:  0:00:51
2021-12-17 20:10:17,458 - Eval - INFO - Avg accuracy Top 1: 0.220011 Avg accuracy Top 5: 0.346487 on validation Dataset
2021-12-17 20:10:17,461 - TensorFlowAdaround - INFO - Original Model Top-1 accuracy = 0.22

**Comment by PaulZhangIsing** [comment]
If I set the bgr=True, the accuracy is higher. However, my data format is in RGB which is strange

**Comment by quic-hitameht** [comment]
Hello @PaulZhangIsing Adaround only supports model using channel_last data format (which is also default) and does not support channel_first data format.

Closing this as resolved. If there is another question please re-open or create a new issue. Thank you.
