### ISSUE TITLE
Examples not using GPU

### ISSUE THREAD

**Issue by ghost** [quic/aimet#899]
Thank you for interesting repo.
I installed AIMET using Dockerfile.torch-gpu and tried to run Examples for torch quantization.
I only use ImageNet subset with 200 classes and 5 per each but it took several time for 1 epochs and when i check GPU process, model quantization didn't use GPU.
You've encountered this issue ever, haven't you?

**Comment by quic-ssiddego** [comment]
Hi @awl-thuong-nguyen  Sorry about the delayed response on this.  Please do check this example to use the GPU mode of execution : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer_GPU.py#L85. Please do let me know if you have further questions.
