### ISSUE TITLE
Yolov5 Support

### ISSUE THREAD

**Issue by bomerzz** [quic/aimet#910]
Hi there,

Currently the library does not support the conversion of Yolov5 models and will fail with the following error because of missing attributes in the StaticGridQuantWrapper. It fails while trying to quantize the following layer:

```
(13): C3(
      (cv1): Conv(
        (conv): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1))
        (act): SiLU(inplace=True)
      )

```
Error thrown by yolo.py
` m_.f, m_.type, m_.np = i, f, t, np # attach index, 'from' index, type, number params`

Is there a workaround to disable quantisation for a specific layer? From my understanding we can only disable entire op_types in the config file and not a specific layer or I might be missing something.

Thanks for your help!

**Comment by LLNLanLeN** [comment]
@bomerzz not sure if this is the information you're looking for, but I think the conversion fail because "SiLU" isn't a supported onnx layer:

https://github.com/onnx/onnx/blob/main/docs/Operators.md

Perhaps you should consider switching SiLU out with a different activation layers instead.

**Comment by bomerzz** [comment]
Hi @LLNLanLeN , I tried replacing SiLU with ReLU however it still does not work. I have a feeling that it might be something to do with the C3 block since al other conv2D layers are able to quantize and the process only fails on layer 13 which is a C3 layer. It seems that the C3 layer cannot accept _StaticGridQuantWrapper_ type as an input from the previous layer.

**Comment by LLNLanLeN** [comment]
that is very surprising. Perhaps the C3 layer isn't an actually `nn.Module` layer, which might cause the issue? Unfortunately I don't know how to skip a specific layer. But perhaps you can try modifying the source code itself?

https://github.com/quic/aimet/blob/53c8dca2def4aba289a4d852bcebe74212036548/TrainingExtensions/torch/src/python/aimet_torch/quantsim.py#L829

I'm seeing here where they add quantization wrappers here.

**Comment by quic-ssiddego** [comment]
@bomerzz  Sorry about the delayed response on this.  Could you please share the logs from your run (w.r.t "tried replacing SiLU with ReLU" test ).   Also, could you please run the model validator and share your observations. https://github.com/quic/aimet/blob/d44b946dfb22850108ebd653fe8b3e9fbfe2124c/Docs/torch_code_examples/model_validator_code_example.py#L138

**Comment by tucachmo2202** [comment]
> @bomerzz not sure if this is the information you're looking for, but I think the conversion fail because "SiLU" isn't a supported onnx layer:
> 
> https://github.com/onnx/onnx/blob/main/docs/Operators.md
> 
> Perhaps you should consider switching SiLU out with a different activation layers instead.

I see that Onnx not consider SiLU as a node. It is x∗σ(x) and visualize like 
![image](https://user-images.githubusercontent.com/47667644/167790922-2986aa76-8f00-497c-9d06-6b1a37d94d6e.png)
