### ISSUE TITLE
Model Quantization Problems

### ISSUE THREAD

**Issue by lblbk** [quic/aimet#942]
I need to split a large model into three smaller models, how can these three models be quantitatively trained at the same time?
thx.

**Comment by quic-ssiddego** [comment]
Hi @lblbk Could you please elaborate on the model architecture and provide more context, such as training framework used? And, AIMET offers algorithms for compression of model and model quantization. Please find more information here : https://github.com/quic/aimet#readme . Please let us know if you have further questions.

**Comment by lblbk** [comment]
Thx for you reply.
My model consists of three parts, backbone, decoder and refiner.The original plan was to train the entire model together.But this is too slow, so the calculation divides them into three parts, similar to a cascaded network.
My training framework is pytorch and Finetuning with aimet.
