### ISSUE TITLE
How to save quantization after post-train quantization? 

### ISSUE THREAD

**Issue by matinhosseiny** [quic/aimet#969]
I tried to save the model after quantization and all the weights were 32 bit. how should I save the model here is my code:

bc_quantizer = QuantizationSimModel(model=model,
                                    quant_scheme=quant_scheme,
                                    dummy_input=dummy_input,
                                    rounding_mode=rounding_mode,
                                    default_output_bw=default_output_bw,
                                    default_param_bw=default_param_bw,
                                    in_place=False)

bc_quantizer.compute_encodings(forward_pass_callback=partial(data_pipeline.evaluate,
                                                             use_cuda=config['use_cuda']),
                               forward_pass_callback_args=num_batches)

torch.save(model, os.path.join(config['logdir'], 'quantized_model.pth'))

**Comment by quic-ssiddego** [comment]
Hi @matinhosseiny  Please refer to this example to export your model after quantsim https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L961. You can export the model using bc_quantizer.export() as shown here : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L981. Please let us know if you have further questions.

**Comment by matinhosseiny** [comment]
I am using the export but all the weights are 32 bit, I have checked both onnx and pth files. I am following the post-training quantization for PyTorch.
https://github.com/quic/aimet/blob/develop/Examples/torch/quantization/cle_bc.ipynb

**Comment by quic-ssiddego** [comment]
@matinhosseiny Post training quantization implements this https://arxiv.org/pdf/1906.04721.pdf . This essentially means by applying CLE and BC you could make the models more conducive for integer math (fixed point). For simulating quantization - please refer to this example : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L585

**Comment by xuyun224** [comment]
@matinhosseiny Have you solved it, how can I get the model of int8

**Comment by quic-hitameht** [comment]
Hi @xuyun224 @matinhosseiny AIMET Quantization Simulation feature provides functionality to simulate the effect of quantized hardware. After the simulation, the model weights will remain in FP32 bits only. But it will export encodings file containing quantization scale/offset for activations and weight tensors in the model which can be ingested by hardware runtime.

Closing this as resolved. If there is another question please re-open or create a new issue.
