### ISSUE TITLE
Per Channel Quantiztion

### ISSUE THREAD

**Issue by yakovdan** [quic/aimet#989]
Hi All, 
It looks like per channel quantization is a work in progress for PyTorch. Is there any sort of a time table or roadmap for this?

Also, what about integration with SNPE? At present, snpe-dlc-quantize has a "--axis_quant" flag that doesn't seem to be doing anything.

Thanks

**Comment by quic-ssiddego** [comment]
Hi @yakovdan Thank you for your query. You can now try the per channel quantization for PyTorch as shown in this example test case : https://github.com/quic/aimet/blob/develop/TrainingExtensions/torch/test/python/test_quantizer.py#L1915. Please do try this out and let us know if you have further queries. Also, for SNPE queries, please check with the SNPE forum: https://developer.qualcomm.com/forums/software/qualcomm-neural-processing-sdk
